language: python
python:
    - "2.7" 
    - "3.2"
    - "3.3"
    - "3.4"

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-5
            - gcc-5

# command to install dependencies      
install:
    - python setup.py install 
    - export CXX="g++-5" CC="gcc-5" LD="g++-5" CXXFLAGS="\-std=c++11"

# command to run tests
script:
    - nosetests
