language: python
python:
    - "2.7" 
    - "3.2"
    - "3.3"
    - "3.4"

# command to install dependencies      
install:
      - pip install -q -e .

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-5

# command to run tests
script:
      - nosetests
