# Toolchain axis: Clang.
# Composes with debug/release and any instrumentation axes.
ID = Clang
CC = clang
CXX = clang++
LD = clang++
append-CFLAGS   = -fPIC -Wall
append-CXXFLAGS = -std=c++17 -fPIC -Wall -fdiagnostics-color=auto
append-LDFLAGS  = -fPIC -Wall -Werror -Xlinker --build-id
