#!/bin/sh
# Pre-build hook: write the appinfo implementation file.
#
# This script is the heart of the "generated implementation, not
# generated header" pattern. The output is a single .cpp that defines
# the symbols declared in appinfo.hpp; bumping APP_VERSION changes
# only this file's content_hash, so only the one .o invalidates.
# appinfo.hpp itself is stable, so PCH and every consumer .o stay
# cached.
#
# Inputs (env, with sane defaults so the example is self-contained):
#   APP_NAME    — defaults to "demo_app"
#   APP_VERSION — defaults to `git describe`, falling back to a literal.
#
# Output path is the first positional argument; it must live next to
# appinfo.hpp so ct-cake's implied-source mechanism picks it up via
# --auto without an explicit target listing.
set -eu

OUT="${1:?usage: gen_appinfo.sh <output.cpp>}"
NAME="${APP_NAME:-demo_app}"
VERSION="${APP_VERSION:-$(git describe --always --dirty 2>/dev/null || echo 0.0.0-dev)}"

mkdir -p "$(dirname "$OUT")"
cat > "$OUT" <<EOF
// AUTO-GENERATED by gen_appinfo.sh — do not edit.
#include "appinfo.hpp"

namespace appinfo {

const char* const name    = "${NAME}";
const char* const version = "${VERSION}";

}  // namespace appinfo
EOF
