"""Bazel backend — generates BUILD.bazel files from a BuildGraph.

Aggregates low-level compile/link rules back into high-level Bazel
cc_binary targets, since Bazel operates at a higher abstraction level
than Make/Ninja.
"""

from __future__ import annotations

import os
import shutil
import subprocess

import compiletools.filesystem_utils
import compiletools.wrappedos
from compiletools.build_backend import (
    BuildBackend,
    aggregate_rule_sources,
    build_obj_info,
    extract_linkopts,
    mangle_target_name,
    register_backend,
)
from compiletools.build_graph import BuildGraph


@register_backend
class BazelBackend(BuildBackend):
    """Generate and execute Bazel build files.

    Note: --file-locking is not applied to this backend. Bazel manages its
    own build sandbox and parallelism; external file locking would conflict
    with its internal coordination.
    """

    @staticmethod
    def name() -> str:
        return "bazel"

    @staticmethod
    def tool_command() -> tuple[str, ...]:
        # Either bazel or bazelisk satisfies this backend.
        return ("bazel", "bazelisk")

    @staticmethod
    def build_filename() -> str:
        return "BUILD.bazel"

    def generate(self, graph: BuildGraph, output=None) -> None:
        graph = self._apply_build_only_changed(graph)

        if output is not None:
            # When writing to a file handle, try to determine the base directory
            # from the file's name attribute (set when opened with open()).
            # When writing to an in-memory buffer (e.g. StringIO in tests),
            # name is not a real path so leave base_dir=None: _bazel_src
            # then returns relative path strings only and never copies
            # source files into ext/.
            base_dir = None
            if hasattr(output, "name") and isinstance(output.name, str) and os.path.isabs(output.name):
                base_dir = os.path.dirname(compiletools.wrappedos.realpath(output.name))
            self._write_build(graph, output, base_dir=base_dir)
        else:
            filename = self.build_filename()
            base_dir = os.path.dirname(compiletools.wrappedos.realpath(filename)) or "."
            with compiletools.filesystem_utils.atomic_output_file(filename, mode="w", encoding="utf-8") as f:
                self._write_build(graph, f, base_dir=base_dir)
            self._ensure_workspace(base_dir)

    def _write_build(self, graph: BuildGraph, f, base_dir: str | None = None) -> None:
        f.write("# BUILD.bazel generated by compiletools\n")

        # Identify test executable paths so we can emit cc_test instead of cc_binary
        test_exe_paths = set()
        if self.args.tests:
            for source in self.args.tests:
                test_exe_paths.add(self.namer.executable_pathname(compiletools.wrappedos.realpath(source)))

        has_binaries = bool(graph.rules_by_type("link")) or bool(graph.rules_by_type("shared_library"))
        has_libraries = bool(graph.rules_by_type("static_library"))
        has_tests = any(r.output in test_exe_paths for r in graph.rules_by_type("link"))
        has_non_test_binaries = has_binaries and (
            bool(graph.rules_by_type("shared_library"))
            or any(r.output not in test_exe_paths for r in graph.rules_by_type("link"))
        )
        if has_non_test_binaries:
            f.write('load("@rules_cc//cc:cc_binary.bzl", "cc_binary")\n')
        if has_libraries:
            f.write('load("@rules_cc//cc:cc_library.bzl", "cc_library")\n')
        if has_tests:
            f.write('load("@rules_cc//cc:cc_test.bzl", "cc_test")\n')

        if base_dir is None:
            base_dir = os.getcwd()

        obj_info = build_obj_info(graph, strip_includes=True)

        for rule in graph.rules_by_type("static_library"):
            srcs, all_copts = aggregate_rule_sources(rule, obj_info)
            target_name = mangle_target_name(os.path.basename(rule.output))
            rel_srcs = sorted(set(self._bazel_src(s, base_dir) for s in srcs))
            self._emit_target(f, "cc_library", target_name, rel_srcs, all_copts)

        for rule in graph.rules_by_type("shared_library"):
            srcs, all_copts = aggregate_rule_sources(rule, obj_info)
            object_files = set(rule.inputs)
            linkopts = self._resolve_linkopts(extract_linkopts(rule.command, object_files) if rule.command else [])
            target_name = mangle_target_name(os.path.basename(rule.output))
            rel_srcs = sorted(set(self._bazel_src(s, base_dir) for s in srcs))
            self._emit_target(f, "cc_binary", target_name, rel_srcs, all_copts, linkopts, linkshared=True)

        for rule in graph.rules_by_type("link"):
            srcs, all_copts = aggregate_rule_sources(rule, obj_info)
            object_files = set(rule.inputs)
            linkopts = self._resolve_linkopts(extract_linkopts(rule.command, object_files) if rule.command else [])
            target_name = mangle_target_name(os.path.basename(rule.output))
            rel_srcs = sorted(set(self._bazel_src(s, base_dir) for s in srcs))
            kind = "cc_test" if rule.output in test_exe_paths else "cc_binary"
            self._emit_target(f, kind, target_name, rel_srcs, all_copts, linkopts)

    @staticmethod
    def _emit_target(
        f,
        kind: str,
        target_name: str,
        rel_srcs: list[str],
        all_copts: list[str],
        linkopts: list[str] | None = None,
        *,
        linkshared: bool = False,
    ) -> None:
        """Write a single ``cc_library`` / ``cc_binary`` / ``cc_test`` stanza."""
        f.write(f"\n{kind}(\n")
        f.write(f'    name = "{target_name}",\n')
        if rel_srcs:
            f.write("    srcs = [\n")
            for s in rel_srcs:
                f.write(f'        "{s}",\n')
            f.write("    ],\n")
        if all_copts:
            f.write("    copts = [\n")
            for c in all_copts:
                f.write(f'        "{c}",\n')
            f.write("    ],\n")
        if linkopts:
            f.write("    linkopts = [\n")
            for opt in linkopts:
                f.write(f'        "{opt}",\n')
            f.write("    ],\n")
        if linkshared:
            f.write("    linkshared = True,\n")
        f.write(")\n")

    @staticmethod
    def _resolve_linkopts(linkopts: list[str]) -> list[str]:
        """Resolve relative -L paths to absolute.

        Bazel executes the linker from a sandbox, so relative paths
        would not resolve to the correct directory.
        """
        resolved = []
        for opt in linkopts:
            if opt.startswith("-L") and not os.path.isabs(opt[2:]):
                resolved.append(f"-L{compiletools.wrappedos.realpath(opt[2:])}")
            else:
                resolved.append(opt)
        return resolved

    @staticmethod
    def _bazel_src(source: str, base_dir: str | None) -> str:
        """Return a Bazel-safe relative source path (PURE, no I/O).

        Bazel rejects target paths containing '..'.  When a source file
        lives outside the workspace this only computes the path that
        ``_prepare_external_sources`` would later copy to under
        ``<base_dir>/ext/<basename>``; nothing is created on disk here so
        ``generate()`` to a StringIO is side-effect-free.

        When *base_dir* is None (e.g. writing to an unnamed in-memory
        buffer) we cannot compute a meaningful relative path, so fall
        back to the source's realpath.
        """
        if base_dir is None:
            return compiletools.wrappedos.realpath(source)

        rel = os.path.relpath(source, base_dir)
        if not rel.startswith(".."):
            return rel

        # Source is outside the workspace — the corresponding copy will
        # live under <base_dir>/ext/<basename>; compute the would-be path
        # without touching the filesystem. The actual copy happens in
        # _prepare_external_sources(), invoked from generate() after the
        # Bazel build file has been written.
        if os.path.exists(source):
            dest = os.path.join(base_dir, "ext", os.path.basename(source))
            return os.path.relpath(dest, base_dir)

        # Source doesn't exist (e.g. mock/test paths) — use absolute path.
        return compiletools.wrappedos.realpath(source)

    def _prepare_external_sources(self, graph: BuildGraph, base_dir: str) -> None:
        """Copy out-of-workspace source files into ``<base_dir>/ext/``.

        Mirrors the path computation in ``_bazel_src`` but performs the
        actual filesystem mutation. Split out of ``_bazel_src`` so that
        ``generate()`` can compute path strings without I/O (e.g. for
        tests that write to a StringIO) and only invoke this step when
        actually preparing for a real Bazel build.
        """
        ext_dir = os.path.join(base_dir, "ext")
        ext_made = False
        obj_info = build_obj_info(graph, strip_includes=True)
        for rule in graph.rules:
            srcs, _ = aggregate_rule_sources(rule, obj_info)
            for source in srcs:
                rel = os.path.relpath(source, base_dir)
                if not rel.startswith(".."):
                    continue
                if not os.path.exists(source):
                    continue
                if not ext_made:
                    os.makedirs(ext_dir, exist_ok=True)
                    ext_made = True
                dest = os.path.join(ext_dir, os.path.basename(source))
                if not os.path.exists(dest):
                    shutil.copy2(source, dest)

    def _ensure_workspace(self, output_dir: str) -> None:
        """Create minimal WORKSPACE and MODULE.bazel files if none exist."""
        workspace_path = os.path.join(output_dir, "WORKSPACE")
        if not os.path.exists(workspace_path):
            with open(workspace_path, "w") as f:
                f.write("# WORKSPACE generated by compiletools\n")
        module_path = os.path.join(output_dir, "MODULE.bazel")
        if not os.path.exists(module_path):
            with open(module_path, "w") as f:
                f.write('module(name = "compiletools_project")\n')
                f.write('bazel_dep(name = "rules_cc", version = "0.1.1")\n')

    def _all_outputs_current(self, graph: BuildGraph) -> bool:
        """Always re-execute the build.

        The base-class pre-check looks for compile/link outputs at the
        ``namer``-derived objdir/exedir paths.  Bazel builds in
        ``bazel-bin/`` (and uses its own action cache), so those paths
        are almost never populated by Bazel itself — the pre-check would
        return False "by accident" and skip the post-build copy of
        binaries from ``bazel-bin`` to ``topbindir``.  Make the contract
        explicit: always defer to Bazel, which has its own incremental
        build logic, and guarantee the post-build copy runs every time
        so the user-visible ``bin/`` stays in sync.
        """
        return False

    def _execute_build(self, target: str) -> None:
        tool = shutil.which("bazelisk") or shutil.which("bazel")
        if tool is None:
            raise RuntimeError("Neither 'bazelisk' nor 'bazel' found on PATH")

        # Materialise out-of-workspace sources into <base_dir>/ext/ now,
        # immediately before the actual Bazel build. Done here (not in
        # generate()) so that generate() to a StringIO stays a pure file
        # emission — no orphan ext/ dirs from test runs.
        if self._graph is not None:
            base_dir = os.path.dirname(compiletools.wrappedos.realpath(self.build_filename())) or "."
            self._prepare_external_sources(self._graph, base_dir)

        if target in ("build", "all"):
            bazel_target = "//:all"
        else:
            bazel_target = f"//:{target}"

        # Startup options (before the "build" subcommand)
        startup_args = [tool]
        system_cacerts = "/etc/pki/ca-trust/extracted/java/cacerts"
        if os.path.exists(system_cacerts):
            startup_args.extend(
                [
                    f"--host_jvm_args=-Djavax.net.ssl.trustStore={system_cacerts}",
                    "--host_jvm_args=-Djavax.net.ssl.trustStorePassword=changeit",
                ]
            )

        cmd = startup_args + [
            "build",
            "--spawn_strategy=local",
            "--action_env=PATH",
        ]
        parallel = getattr(self.args, "parallel", None)
        if parallel:
            cmd.append(f"--jobs={parallel}")
        cmd.append(bazel_target)
        subprocess.check_call(cmd, text=True)

        # Bazel outputs executables to bazel-bin/.  Copy directly to the
        # final output directory (topbindir or --output) to avoid a
        # redundant intermediate copy through objdir.
        bazel_bin = os.path.join(os.getcwd(), "bazel-bin")
        if os.path.isdir(bazel_bin):
            dest = getattr(self.args, "output", None) or self.namer.topbindir()
            self._copy_built_executables(bazel_bin, dest_dir=dest)
            self._copy_bazel_libraries(bazel_bin)

    def _copy_bazel_libraries(self, bazel_bin: str) -> None:
        """Copy Bazel-built libraries to namer paths.

        Bazel names libraries lib<target>.a in bazel-bin/.  Walk the
        graph to find expected library outputs and copy them.
        """
        if self._graph is None:
            return
        for lib_type in ("static_library", "shared_library"):
            ext = ".a" if lib_type == "static_library" else ".so"
            for rule in self._graph.rules_by_type(lib_type):
                target_name = mangle_target_name(os.path.basename(rule.output))
                bazel_lib = os.path.join(bazel_bin, f"lib{target_name}{ext}")
                if os.path.exists(bazel_lib):
                    os.makedirs(os.path.dirname(rule.output), exist_ok=True)
                    shutil.copy2(bazel_lib, rule.output)

    def clean(self) -> None:
        """Run bazel clean, then remove build artifact directories."""
        tool = shutil.which("bazelisk") or shutil.which("bazel")
        if tool is not None:
            try:
                subprocess.check_call([tool, "clean"], text=True)
            except subprocess.CalledProcessError:
                pass
        super().clean()

    def realclean(self, graph) -> None:
        """Run bazel clean --expunge, then selectively remove build products."""
        tool = shutil.which("bazelisk") or shutil.which("bazel")
        if tool is not None:
            try:
                subprocess.check_call([tool, "clean", "--expunge"], text=True)
            except subprocess.CalledProcessError:
                pass
        super().realclean(graph)
