"""Bazel backend — generates BUILD.bazel files from a BuildGraph.

Aggregates low-level compile/link rules back into high-level Bazel
cc_binary targets, since Bazel operates at a higher abstraction level
than Make/Ninja.
"""

from __future__ import annotations

import os
import shutil
import subprocess

import compiletools.filesystem_utils
from compiletools.build_backend import BuildBackend, register_backend
from compiletools.build_graph import BuildGraph


def _extract_copts(command: list[str]) -> list[str]:
    """Extract compiler flags from a compile command.

    Strips the compiler binary, -c, source file, -o, and output file,
    returning the remaining flags as copts.  Multi-flag strings (e.g.
    ``"-fPIC -g -Wall"``) are split into individual flags.
    """
    if not command:
        return []
    import shlex

    # Flatten: some elements may be space-joined flag strings
    flat: list[str] = []
    for elem in command[1:]:  # skip compiler binary
        flat.extend(shlex.split(elem))

    copts = []
    skip_next = False
    include_next = False
    for arg in flat:
        if skip_next:
            skip_next = False
            continue
        if include_next:
            # Bazel manages include paths via its own mechanisms;
            # skip -I flags since absolute paths cause sandbox errors.
            include_next = False
            continue
        if arg == "-c":
            continue
        if arg == "-o":
            skip_next = True
            continue
        if arg in ("-I", "-isystem", "-iquote"):
            include_next = True
            continue
        # Skip -I<path> combined forms — Bazel manages includes itself
        if arg.startswith(("-I", "-isystem", "-iquote")):
            continue
        # Skip source files (non-flag arguments that aren't preceded by -o)
        if not arg.startswith("-"):
            continue
        copts.append(arg)
    return copts


def _extract_linkopts(command: list[str], object_files: set[str]) -> list[str]:
    """Extract linker flags from a link command.

    Strips the linker binary, -o, output executable, and object file paths,
    returning the remaining flags as linkopts.  Multi-flag strings are split.
    """
    if not command:
        return []
    import shlex

    flat: list[str] = []
    for elem in command[1:]:
        flat.extend(shlex.split(elem))

    linkopts = []
    skip_next = False
    for arg in flat:
        if skip_next:
            skip_next = False
            continue
        if arg == "-o":
            skip_next = True
            continue
        if arg in object_files:
            continue
        linkopts.append(arg)
    return linkopts


@register_backend
class BazelBackend(BuildBackend):
    """Generate and execute Bazel build files."""

    @staticmethod
    def name() -> str:
        return "bazel"

    @staticmethod
    def build_filename() -> str:
        return "BUILD.bazel"

    def generate(self, graph: BuildGraph, output=None) -> None:
        if output is not None:
            # When writing to a file handle, try to determine the base directory
            # from the file's name attribute (set when opened with open()).
            base_dir = None
            if hasattr(output, "name") and isinstance(output.name, str):
                base_dir = os.path.dirname(os.path.abspath(output.name))
            self._write_build(graph, output, base_dir=base_dir)
        else:
            filename = self.build_filename()
            base_dir = os.path.dirname(os.path.abspath(filename)) or "."
            with compiletools.filesystem_utils.atomic_output_file(filename, mode="w", encoding="utf-8") as f:
                self._write_build(graph, f, base_dir=base_dir)
            self._ensure_workspace(base_dir)

    def _write_build(self, graph: BuildGraph, f, base_dir: str | None = None) -> None:
        f.write("# BUILD.bazel generated by compiletools\n")

        # Only emit the load statement if there are actual cc_binary targets
        if graph.rules_by_type("link"):
            f.write('load("@rules_cc//cc:cc_binary.bzl", "cc_binary")\n')

        if base_dir is None:
            base_dir = os.getcwd()

        # Build reverse map: object file -> (source, headers, copts)
        obj_info: dict[str, tuple[str, list[str], list[str]]] = {}
        for rule in graph.rules_by_type("compile"):
            source = rule.inputs[0] if rule.inputs else ""
            headers = rule.inputs[1:] if len(rule.inputs) > 1 else []
            copts = _extract_copts(rule.command) if rule.command else []
            obj_info[rule.output] = (source, headers, copts)

        # For each link rule, aggregate into a cc_binary
        for rule in graph.rules_by_type("link"):
            object_files = set(rule.inputs)
            srcs = []
            all_copts = []
            seen_copts: set[str] = set()

            for obj in rule.inputs:
                if obj in obj_info:
                    source, headers, copts = obj_info[obj]
                    if source:
                        srcs.append(source)
                    srcs.extend(headers)
                    for c in copts:
                        if c not in seen_copts:
                            all_copts.append(c)
                            seen_copts.add(c)

            linkopts = _extract_linkopts(rule.command, object_files) if rule.command else []

            # Derive target name from executable path
            exe_basename = os.path.basename(rule.output)
            target_name = exe_basename.replace(".", "_").replace("-", "_")

            # Make paths relative to BUILD file directory
            rel_srcs = sorted(set(os.path.relpath(s, base_dir) for s in srcs))

            f.write("\ncc_binary(\n")
            f.write(f'    name = "{target_name}",\n')
            if rel_srcs:
                f.write("    srcs = [\n")
                for s in rel_srcs:
                    f.write(f'        "{s}",\n')
                f.write("    ],\n")
            if all_copts:
                f.write("    copts = [\n")
                for c in all_copts:
                    f.write(f'        "{c}",\n')
                f.write("    ],\n")
            if linkopts:
                f.write("    linkopts = [\n")
                for l in linkopts:  # noqa: E741
                    f.write(f'        "{l}",\n')
                f.write("    ],\n")
            f.write(")\n")

    def _ensure_workspace(self, output_dir: str) -> None:
        """Create minimal WORKSPACE and MODULE.bazel files if none exist."""
        workspace_path = os.path.join(output_dir, "WORKSPACE")
        if not os.path.exists(workspace_path):
            with open(workspace_path, "w") as f:
                f.write("# WORKSPACE generated by compiletools\n")
        module_path = os.path.join(output_dir, "MODULE.bazel")
        if not os.path.exists(module_path):
            with open(module_path, "w") as f:
                f.write('module(name = "compiletools_project")\n')
                f.write('bazel_dep(name = "rules_cc", version = "0.1.1")\n')

    def execute(self, target: str = "build") -> None:
        tool = shutil.which("bazelisk") or shutil.which("bazel")
        if tool is None:
            raise RuntimeError("Neither 'bazelisk' nor 'bazel' found on PATH. Try: module load bazelisk-latest")

        if target in ("build", "all"):
            bazel_target = "//:all"
        else:
            bazel_target = f"//:{target}"

        cmd = [tool, "build", bazel_target]
        subprocess.check_call(cmd, universal_newlines=True)
