"""CMake backend — generates CMakeLists.txt from a BuildGraph.

Aggregates low-level compile/link rules back into high-level CMake
targets (add_executable, target_compile_options, etc.), since CMake
operates at a higher abstraction level than Make/Ninja.
"""

from __future__ import annotations

import os
import shlex
import shutil
import subprocess

import compiletools.filesystem_utils
from compiletools.build_backend import BuildBackend, register_backend
from compiletools.build_graph import BuildGraph


def _split_compound_args(args: list[str]) -> list[str]:
    """Split compound space-separated arguments (e.g. CXXFLAGS as one string).

    Uses shlex to correctly handle quoted values like -DFOO='bar baz'.
    """
    result = []
    for arg in args:
        if " " in arg:
            try:
                result.extend(shlex.split(arg))
            except ValueError:
                result.extend(arg.split())
        else:
            result.append(arg)
    return result


def _extract_copts(command: list[str]) -> list[str]:
    """Extract compiler flags from a compile command.

    Strips the compiler binary, -c, source file, -o, and output file,
    returning the remaining flags as copts. Splits multi-word flags
    (e.g. from CXXFLAGS being a single space-separated string).
    Recombines space-separated -I <dir> into -I<dir>.
    """
    if not command:
        return []
    args = _split_compound_args(command[1:])
    copts = []
    skip_next = False
    expect_include_dir = False
    for arg in args:
        if skip_next:
            skip_next = False
            continue
        if expect_include_dir:
            copts.append(f"-I{arg}")
            expect_include_dir = False
            continue
        if arg == "-c":
            continue
        if arg == "-o":
            skip_next = True
            continue
        if arg == "-I":
            expect_include_dir = True
            continue
        if not arg.startswith("-"):
            continue
        copts.append(arg)
    return copts


def _extract_linkopts(command: list[str], object_files: set[str]) -> list[str]:
    """Extract linker flags from a link command.

    Strips the linker binary, -o, output executable, and object file paths,
    returning the remaining flags as linkopts. Splits multi-word flags.
    """
    if not command:
        return []
    args = _split_compound_args(command[1:])
    linkopts = []
    skip_next = False
    for arg in args:
        if skip_next:
            skip_next = False
            continue
        if arg == "-o":
            skip_next = True
            continue
        if arg in object_files:
            continue
        linkopts.append(arg)
    return linkopts


def _separate_include_dirs(copts: list[str]) -> tuple[list[str], list[str]]:
    """Separate -I flags from other compiler options.

    Returns (include_dirs, remaining_copts) where include_dirs contains
    the directory paths (without -I prefix) and remaining_copts has
    everything else.
    """
    include_dirs = []
    remaining = []
    for opt in copts:
        if opt.startswith("-I"):
            include_dirs.append(opt[2:])
        else:
            remaining.append(opt)
    return include_dirs, remaining


@register_backend
class CMakeBackend(BuildBackend):
    """Generate and execute CMake build files."""

    @staticmethod
    def name() -> str:
        return "cmake"

    @staticmethod
    def build_filename() -> str:
        return "CMakeLists.txt"

    def generate(self, graph: BuildGraph, output=None) -> None:
        if output is not None:
            self._write_cmake(graph, output)
        else:
            filename = self.build_filename()
            with compiletools.filesystem_utils.atomic_output_file(filename, mode="w", encoding="utf-8") as f:
                self._write_cmake(graph, f)

    def _write_cmake(self, graph: BuildGraph, f) -> None:
        f.write("# CMakeLists.txt generated by compiletools\n")
        f.write("cmake_minimum_required(VERSION 3.15)\n")
        f.write("project(compiletools_build CXX)\n")

        # Build reverse map: object file -> (source, headers, copts)
        obj_info: dict[str, tuple[str, list[str], list[str]]] = {}
        for rule in graph.rules_by_type("compile"):
            source = rule.inputs[0] if rule.inputs else ""
            headers = rule.inputs[1:] if len(rule.inputs) > 1 else []
            copts = _extract_copts(rule.command) if rule.command else []
            obj_info[rule.output] = (source, headers, copts)

        # For each link rule, aggregate into an add_executable
        for rule in graph.rules_by_type("link"):
            object_files = set(rule.inputs)
            srcs = []
            all_copts = []
            seen_copts: set[str] = set()

            for obj in rule.inputs:
                if obj in obj_info:
                    source, headers, copts = obj_info[obj]
                    if source:
                        srcs.append(source)
                    srcs.extend(headers)
                    for c in copts:
                        if c not in seen_copts:
                            all_copts.append(c)
                            seen_copts.add(c)

            linkopts = _extract_linkopts(rule.command, object_files) if rule.command else []

            # Derive target name from executable path
            exe_basename = os.path.basename(rule.output)
            target_name = exe_basename.replace(".", "_").replace("-", "_")

            # Separate -I flags into target_include_directories
            include_dirs, remaining_copts = _separate_include_dirs(all_copts)

            rel_srcs = sorted(set(srcs))

            f.write(f"\nadd_executable({target_name}\n")
            for s in rel_srcs:
                f.write(f"    {s}\n")
            f.write(")\n")

            if remaining_copts:
                quoted = " ".join(f'"{c}"' for c in remaining_copts)
                f.write(f"target_compile_options({target_name} PRIVATE {quoted})\n")

            if include_dirs:
                quoted = " ".join(f'"{d}"' for d in include_dirs)
                f.write(f"target_include_directories({target_name} PRIVATE {quoted})\n")

            if linkopts:
                quoted = " ".join(f'"{l}"' for l in linkopts)
                f.write(f"target_link_options({target_name} PRIVATE {quoted})\n")

    def execute(self, target: str = "build") -> None:
        cmake = shutil.which("cmake")
        if cmake is None:
            raise RuntimeError("'cmake' not found on PATH")

        # Use out-of-source build in {objdir}/cmake-build
        source_dir = os.path.dirname(os.path.abspath(self.build_filename()))
        build_dir = os.path.join(self.args.objdir, "cmake-build")
        os.makedirs(build_dir, exist_ok=True)

        # Configure
        configure_cmd = [cmake, "-S", source_dir, "-B", build_dir]
        subprocess.check_call(configure_cmd, universal_newlines=True)

        # Build
        build_cmd = [cmake, "--build", build_dir]
        if hasattr(self.args, "parallel") and self.args.parallel:
            build_cmd.extend(["--parallel", str(self.args.parallel)])
        if target not in ("build", "all"):
            build_cmd.extend(["--target", target])
        subprocess.check_call(build_cmd, universal_newlines=True)

        # Copy built executables to bindir
        if hasattr(self.args, "bindir") and self.args.bindir:
            os.makedirs(self.args.bindir, exist_ok=True)
            for dirpath, _dirs, files in os.walk(build_dir):
                for fname in files:
                    full = os.path.join(dirpath, fname)
                    if os.access(full, os.X_OK) and not fname.endswith(".cmake"):
                        dest = os.path.join(self.args.bindir, fname)
                        shutil.copy2(full, dest)
