"""CMake backend — generates CMakeLists.txt from a BuildGraph.

Aggregates low-level compile/link rules back into high-level CMake
targets (add_executable, target_compile_options, etc.), since CMake
operates at a higher abstraction level than Make/Ninja.
"""

from __future__ import annotations

import os
import shutil
import subprocess

import compiletools.filesystem_utils
import compiletools.utils
from compiletools.build_backend import (
    BuildBackend,
    aggregate_rule_sources,
    extract_copts,
    extract_linkopts,
    mangle_target_name,
    register_backend,
)
from compiletools.build_graph import BuildGraph


def _separate_include_dirs(copts: list[str]) -> tuple[list[str], list[str]]:
    """Separate -I flags from other compiler options.

    Returns (include_dirs, remaining_copts) where include_dirs contains
    the directory paths (without -I prefix) and remaining_copts has
    everything else.
    """
    include_dirs = []
    remaining = []
    for opt in copts:
        if opt.startswith("-I"):
            include_dirs.append(opt[2:])
        else:
            remaining.append(opt)
    return include_dirs, remaining


@register_backend
class CMakeBackend(BuildBackend):
    """Generate and execute CMake build files."""

    @staticmethod
    def name() -> str:
        return "cmake"

    @staticmethod
    def build_filename() -> str:
        return "CMakeLists.txt"

    def generate(self, graph: BuildGraph, output=None) -> None:
        self._graph = graph
        if output is not None:
            self._write_cmake(graph, output)
        else:
            filename = self.build_filename()
            with compiletools.filesystem_utils.atomic_output_file(filename, mode="w", encoding="utf-8") as f:
                self._write_cmake(graph, f)

    def _write_cmake(self, graph: BuildGraph, f) -> None:
        f.write("# CMakeLists.txt generated by compiletools\n")
        f.write("cmake_minimum_required(VERSION 3.15)\n")

        has_c = False
        has_cxx = False
        for rule in graph.rules_by_type("compile"):
            if rule.inputs and compiletools.utils.is_c_source(rule.inputs[0]):
                has_c = True
            else:
                has_cxx = True
        if has_c and not has_cxx:
            lang = "C"
        elif has_c and has_cxx:
            lang = "C CXX"
        else:
            lang = "CXX"
        f.write(f"project(compiletools_build {lang})\n")

        obj_info: dict[str, tuple[str, list[str], list[str]]] = {}
        for rule in graph.rules_by_type("compile"):
            source = rule.inputs[0] if rule.inputs else ""
            headers = rule.inputs[1:] if len(rule.inputs) > 1 else []
            copts = extract_copts(rule.command) if rule.command else []
            obj_info[rule.output] = (source, headers, copts)

        for lib_type in ("static_library", "shared_library"):
            for rule in graph.rules_by_type(lib_type):
                srcs, all_copts = aggregate_rule_sources(rule, obj_info)
                target_name = mangle_target_name(os.path.basename(rule.output))
                include_dirs, remaining_copts = _separate_include_dirs(all_copts)
                rel_srcs = sorted(set(srcs))
                cmake_type = "STATIC" if lib_type == "static_library" else "SHARED"

                f.write(f"\nadd_library({target_name} {cmake_type}\n")
                for s in rel_srcs:
                    f.write(f"    {s}\n")
                f.write(")\n")

                if remaining_copts:
                    quoted = " ".join(f'"{c}"' for c in remaining_copts)
                    f.write(f"target_compile_options({target_name} PRIVATE {quoted})\n")

                if include_dirs:
                    quoted = " ".join(f'"{d}"' for d in include_dirs)
                    f.write(f"target_include_directories({target_name} PRIVATE {quoted})\n")

        for rule in graph.rules_by_type("link"):
            srcs, all_copts = aggregate_rule_sources(rule, obj_info)
            object_files = set(rule.inputs)
            linkopts = extract_linkopts(rule.command, object_files) if rule.command else []
            target_name = mangle_target_name(os.path.basename(rule.output))
            include_dirs, remaining_copts = _separate_include_dirs(all_copts)
            rel_srcs = sorted(set(srcs))

            f.write(f"\nadd_executable({target_name}\n")
            for s in rel_srcs:
                f.write(f"    {s}\n")
            f.write(")\n")

            if remaining_copts:
                quoted = " ".join(f'"{c}"' for c in remaining_copts)
                f.write(f"target_compile_options({target_name} PRIVATE {quoted})\n")

            if include_dirs:
                quoted = " ".join(f'"{d}"' for d in include_dirs)
                f.write(f"target_include_directories({target_name} PRIVATE {quoted})\n")

            if linkopts:
                quoted = " ".join(f'"{opt}"' for opt in linkopts)
                f.write(f"target_link_options({target_name} PRIVATE {quoted})\n")

    def execute(self, target: str = "build") -> None:
        if target == "runtests":
            self._run_tests()
            return

        if self._graph is not None and self._all_outputs_current(self._graph):
            return

        cmake = shutil.which("cmake")
        if cmake is None:
            raise RuntimeError("'cmake' not found on PATH")

        # Use out-of-source build in {objdir}/cmake-build
        source_dir = os.path.dirname(os.path.abspath(self.build_filename()))
        build_dir = os.path.join(self.args.objdir, "cmake-build")
        os.makedirs(build_dir, exist_ok=True)

        # Configure
        configure_cmd = [cmake, "-S", source_dir, "-B", build_dir]
        subprocess.check_call(configure_cmd, universal_newlines=True)

        # Build
        build_cmd = [cmake, "--build", build_dir]
        if hasattr(self.args, "parallel") and self.args.parallel:
            build_cmd.extend(["--parallel", str(self.args.parallel)])
        if target not in ("build", "all"):
            build_cmd.extend(["--target", target])
        subprocess.check_call(build_cmd, universal_newlines=True)

        # Copy built executables to namer.executable_pathname() locations
        # so _copyexes() can find them.
        self._copy_built_executables(build_dir)
        if self._graph is not None:
            self._record_link_signatures(self._graph)
