"""Makefile backend — generates GNU Makefiles from a BuildGraph."""

from __future__ import annotations

import subprocess

import compiletools.makefile
from compiletools.build_backend import BuildBackend, register_backend
from compiletools.build_graph import BuildGraph


@register_backend
class MakefileBackend(BuildBackend):
    """Generate and execute GNU Makefiles."""

    @staticmethod
    def name() -> str:
        return "make"

    @staticmethod
    def build_filename() -> str:
        return "Makefile"

    def generate(self, graph: BuildGraph, output=None) -> None:
        """Write Makefile from BuildGraph.

        Args:
            graph: The build graph to render.
            output: A file-like object to write to. If None, delegates to
                MakefileCreator for full-featured Makefile generation.
        """
        self._graph = graph
        if output is not None:
            self._write_makefile(graph, output)
        else:
            creator = compiletools.makefile.MakefileCreator(self.args, self.hunter)
            creator.create()

    def _write_makefile(self, graph: BuildGraph, f) -> None:
        f.write(f"# Makefile generated by {self.args}\n\n")
        f.write(".DELETE_ON_ERROR:\n\n")
        for rule in graph.rules:
            if rule.rule_type == "phony":
                f.write(f".PHONY: {rule.output}\n")
            line = f"{rule.output}: {' '.join(rule.inputs)}"
            if rule.order_only_deps:
                line += f" | {' '.join(rule.order_only_deps)}"
            f.write(line + "\n")
            if rule.command:
                f.write("\t" + " ".join(rule.command) + "\n")
            f.write("\n")

    def execute(self, target: str = "build") -> None:
        """Run GNU make."""
        if self._graph is not None and self._all_outputs_current(self._graph):
            return

        cmd = ["make"]
        if self.args.verbose <= 1:
            cmd.append("-s")
        if self.args.verbose >= 4:
            # --trace first comes in GNU make 4.0
            try:
                make_version = (
                    subprocess.check_output(["make", "--version"], universal_newlines=True)
                    .splitlines()[0]
                    .split(" ")[-1]
                    .split(".")[0]
                )
                if int(make_version) >= 4:
                    cmd.append("--trace")
            except (subprocess.CalledProcessError, ValueError, IndexError):
                pass  # Skip --trace if version detection fails
        cmd.extend(["-j", str(getattr(self.args, "parallel", 1))])
        cmd.extend(["-f", self.args.makefilename, target])
        if self.args.verbose >= 1:
            print(" ".join(cmd))
        subprocess.check_call(cmd, universal_newlines=True)
        if self._graph is not None:
            self._record_link_signatures(self._graph)
