"""Makefile backend — generates GNU Makefiles from a BuildGraph."""

from __future__ import annotations

import builtins
import functools
import os
import re
import shlex
import subprocess

import compiletools.filesystem_utils
import compiletools.utils
import compiletools.wrappedos
from compiletools.build_backend import (
    BuildBackend,
    register_backend,
)
from compiletools.build_graph import BuildGraph


@functools.lru_cache(maxsize=1)
def _get_make_version() -> tuple[int, int]:
    """Detect GNU Make version. Returns (major, minor) or (0, 0) on failure."""
    try:
        line = subprocess.check_output(["make", "--version"], text=True).splitlines()[0]
        m = re.search(r"(\d+)\.(\d+)", line)
        if not m:
            return (0, 0)
        return (int(m.group(1)), int(m.group(2)))
    except (subprocess.CalledProcessError, ValueError, IndexError, FileNotFoundError):
        return (0, 0)


@register_backend
class MakefileBackend(BuildBackend):
    """Generate and execute GNU Makefiles."""

    @staticmethod
    def name() -> str:
        return "make"

    @staticmethod
    def tool_command() -> str:
        return "make"

    @staticmethod
    def build_filename() -> str:
        return "Makefile"

    @staticmethod
    def add_arguments(cap) -> None:
        """Register Make-specific CLI arguments.

        Safe to call more than once on the same parser.
        """
        if compiletools.apptools._parser_has_option(cap, "--makefilename"):
            return
        cap.add(
            "--makefilename",
            default="Makefile",
            help="Output filename for the Makefile",
        )
        cap.add(
            "--build-only-changed",
            help="Only build the binaries depending on the source or header absolute "
            "filenames in this space-delimited list.",
        )
        compiletools.apptools.add_locking_arguments(cap)
        compiletools.utils.add_flag_argument(
            parser=cap,
            name="serialise-tests",
            dest="serialisetests",
            default=False,
            help="Force the unit tests to run serially rather than in parallel. "
            "Defaults to false because it is slower.",
        )
        compiletools.utils.add_flag_argument(
            parser=cap,
            name="shuffle",
            dest="shuffle",
            default=False,
            help="Pass --shuffle to GNU Make (>= 4.4) to randomize prerequisite ordering. "
            "Useful for CI to detect missing dependencies.",
        )

    def generate(self, graph: BuildGraph, output=None) -> None:
        """Write Makefile from BuildGraph.

        Args:
            graph: The build graph to render.
            output: A file-like object to write to. If None, writes to
                the file specified by args.makefilename.
        """
        self._setup_file_locking()
        graph = self._apply_build_only_changed(graph)

        if output is not None:
            self._write_makefile(graph, output)
        else:
            if self._build_file_uptodate(graph):
                return
            with compiletools.filesystem_utils.atomic_output_file(
                self.args.makefilename, mode="w", encoding="utf-8"
            ) as f:
                self._write_makefile(graph, f)

    def _build_file_uptodate(self, graph: BuildGraph) -> bool:
        """Check if the Makefile needs regeneration.

        Compares the args signature in the Makefile header and checks mtimes
        of every input referenced by a build rule (compile, link, library,
        test, copy). Phony and mkdir rules have no real inputs.
        """
        try:
            makefilemtime = compiletools.wrappedos.getmtime(self.args.makefilename)
        except OSError:
            if self.args.verbose > 7:
                print("Regenerating Makefile.")
                print(f"Could not determine mtime for {self.args.makefilename}. Assuming that it doesn't exist.")
            return False

        expected = f"# Makefile generated by {self.args}"
        with builtins.open(self.args.makefilename, encoding="utf-8") as mfile:
            previous = mfile.readline().strip()
            if previous != expected:
                if self.args.verbose > 7:
                    print("Regenerating Makefile.")
                    print(f'Previous generation line was "{previous}".')
                    print(f'Current  generation line  is "{expected}".')
                return False
            elif self.args.verbose > 9:
                print("Makefile header line is identical.  Testing mod time of all the files now.")

        # Check mtimes of every build-rule input against the Makefile's mtime.
        # Includes link/library inputs (e.g. linker scripts, additional .o
        # files) so a change to a non-compile dependency triggers regen.
        skip_types = {"phony", "mkdir"}
        for rule in graph.rules:
            if rule.rule_type in skip_types:
                continue
            for dep in rule.inputs:
                try:
                    dep_mtime = compiletools.wrappedos.getmtime(dep)
                except OSError:
                    continue
                if dep_mtime > makefilemtime:
                    if self.args.verbose > 7:
                        print("Regenerating Makefile.")
                        print(f"mtime {dep_mtime} for {dep} is newer than mtime for the Makefile")
                    return False
                elif self.args.verbose > 9:
                    print(
                        f"mtime {dep_mtime} for {dep} is older than "
                        f"mtime for the Makefile. This wont trigger regeneration of the Makefile."
                    )

        if self.args.verbose > 9:
            print("Makefile is up to date.  Not recreating.")
        return True

    @property
    def _timing_enabled(self) -> bool:
        return self._timer is not None

    @property
    def _timing_log_path(self) -> str:
        makefilename = getattr(self.args, "makefilename", "Makefile")
        return os.path.join(os.path.dirname(makefilename) or ".", ".ct-make-timing.jsonl")

    def _write_makefile(self, graph: BuildGraph, f) -> None:
        """Write a complete Makefile from the BuildGraph."""
        f.write(f"# Makefile generated by {self.args}\n\n")
        f.write(".DELETE_ON_ERROR:\n\n")
        f.write("MAKEFLAGS += -rR\n\n")
        if os.path.isfile("/bin/bash"):
            f.write("SHELL := /bin/bash\n\n")

        # Write phony rules first so "all" is the default target
        phony_rules = [r for r in graph.rules if r.rule_type == "phony"]
        non_phony_rules = [r for r in graph.rules if r.rule_type != "phony"]

        # Ensure "all" comes first among phony rules
        phony_rules.sort(key=lambda r: (0 if r.output == "all" else 1, r.output))

        for rule in phony_rules + non_phony_rules:
            if rule.rule_type == "phony":
                f.write(f".PHONY: {rule.output}\n")

            line = f"{rule.output}: {' '.join(rule.inputs)}"
            if rule.order_only_deps:
                line += f" | {' '.join(rule.order_only_deps)}"
            f.write(line + "\n")

            if rule.command:
                recipe = self._format_recipe(rule)
                f.write("\t" + recipe + "\n")
            f.write("\n")

        # Serialise tests: prevent Make from parallelising test execution
        if getattr(self.args, "serialisetests", False) and graph.rules_by_type("test"):
            f.write(".NOTPARALLEL: runtests\n\n")

        # Write clean rules
        self._write_clean_rules(graph, f)

    def _format_recipe(self, rule) -> str:
        """Format a BuildRule's command into a Makefile recipe string."""
        if rule.rule_type == "compile":
            cmd_str = self._wrap_compile_cmd(rule.command)
            if self.args.verbose >= 1:
                # Find the source file (first input)
                source = rule.inputs[0] if rule.inputs else rule.output
                recipe = f"@echo ... {source} ; {cmd_str}"
            else:
                recipe = cmd_str
        elif rule.rule_type in ("link", "shared_library", "static_library"):
            cmd_str = self._wrap_link_cmd(rule.command)
            if self.args.verbose >= 1:
                recipe = f"+@echo ... {rule.output} ; {cmd_str}"
            else:
                recipe = cmd_str
        elif rule.rule_type == "test":
            cmd_str = " ".join(rule.command)
            if self.args.verbose >= 1:
                exe_name = rule.output.removesuffix(".result")
                recipe = f"@echo ... {exe_name} ; {cmd_str}"
            else:
                recipe = cmd_str
        else:
            recipe = " ".join(rule.command)

        if self._timing_enabled and rule.rule_type in ("compile", "link", "shared_library", "static_library"):
            recipe = self._wrap_with_timing(recipe, rule.output)
        return recipe

    def _wrap_with_timing(self, recipe: str, target: str) -> str:
        """Wrap a recipe with shell timing that writes to the JSONL log."""
        log = shlex.quote(self._timing_log_path)
        tgt = shlex.quote(target)
        # Use bash's $EPOCHREALTIME (bash 5+) for sub-second precision,
        # with date +%s%N fallback for older bash
        return (
            f"@_ct_s=$$(date +%s%N 2>/dev/null || echo 0); "
            f"{recipe.lstrip('@+')}; _ct_rc=$$?; "
            f"_ct_e=$$(date +%s%N 2>/dev/null || echo 0); "
            f"echo '{{\"target\":{tgt},\"start_ns\":'$$_ct_s',\"end_ns\":'$$_ct_e'}}' >> {log}; "
            f"exit $$_ct_rc"
        )

    def _write_clean_rules(self, graph: BuildGraph, f) -> None:
        """Write clean and realclean rules to the Makefile."""
        exe_dir = self.namer.executable_dir()
        obj_dir = self.namer.object_dir()

        # Gather all outputs and object files from the graph
        all_outputs = []
        all_objects = []
        for rule in graph.rules:
            if rule.rule_type == "compile":
                all_objects.append(rule.output)
            elif rule.rule_type in ("link", "static_library", "shared_library"):
                all_outputs.append(rule.output)

        # clean rule: remove executables, objects, and empty dirs
        rmcopiedexes = f"find {exe_dir} -type f -executable -delete 2>/dev/null"
        parts = [rmcopiedexes]
        if all_outputs or all_objects:
            parts.append("rm -f " + " ".join(all_outputs + all_objects))
        parts.append(f"find {obj_dir} -type d -empty -delete")
        if exe_dir != obj_dir:
            parts.append(f"find {exe_dir} -type d -empty -delete")
        recipe = ";".join(parts)

        f.write(".PHONY: clean\n")
        f.write("clean:\n")
        f.write(f"\t-{recipe}\n\n")

        # realclean rule: rm -rf the per-project exe_dir, but only this build's
        # products from obj_dir (which may be shared with peer sub-projects).
        # Mirrors BuildBackend.realclean() so `make realclean` and
        # `ct-cake --realclean` are equivalent.
        realclean_parts = [f"rm -rf {exe_dir}"]
        if exe_dir != obj_dir and (all_outputs or all_objects):
            realclean_parts.append("rm -f " + " ".join(all_outputs + all_objects))
            realclean_parts.append(f"find {obj_dir} -type d -empty -delete")
        realclean_recipe = ";".join(realclean_parts)

        f.write(".PHONY: realclean\n")
        f.write("realclean:\n")
        f.write(f"\t-{realclean_recipe}\n\n")

    def _execute_build(self, target: str) -> None:
        # Clean up any stale timing log before the build
        timing_log = self._timing_log_path
        if self._timing_enabled:
            try:
                os.remove(timing_log)
            except FileNotFoundError:
                pass

        make_version = _get_make_version()
        cmd = ["make"]
        if self.args.verbose <= 1:
            cmd.append("-s")
        if self.args.verbose >= 4 and make_version >= (4, 0):
            cmd.append("--trace")
        parallel = getattr(self.args, "parallel", 1)
        if parallel > 1 and make_version >= (4, 0):
            cmd.append("--output-sync=target")
        if getattr(self.args, "shuffle", False) and make_version >= (4, 4):
            cmd.append("--shuffle")
        cmd.extend(["-j", str(parallel)])
        cmd.extend(["-f", self.args.makefilename, target])
        if self.args.verbose >= 1:
            print(" ".join(cmd))
        subprocess.check_call(cmd, text=True)

        # Parse per-file timing from the JSONL log written by instrumented recipes
        timer = self._timer
        if timer and os.path.exists(timing_log):
            timer.record_rules_from_make_timing(timing_log, graph=self._graph)
            try:
                os.remove(timing_log)
            except FileNotFoundError:
                pass
