"""Makefile backend — generates GNU Makefiles from a BuildGraph."""

from __future__ import annotations

import compiletools.filesystem_utils
from compiletools.build_backend import BuildBackend, register_backend
from compiletools.build_graph import BuildGraph


@register_backend
class MakefileBackend(BuildBackend):
    """Generate and execute GNU Makefiles."""

    @staticmethod
    def name() -> str:
        return "make"

    @staticmethod
    def build_filename() -> str:
        return "Makefile"

    def generate(self, graph: BuildGraph, output=None) -> None:
        """Write Makefile from BuildGraph.

        Args:
            graph: The build graph to render.
            output: A file-like object to write to. If None, writes to
                self.args.makefilename using atomic_output_file.
        """
        if output is not None:
            self._write_makefile(graph, output)
        else:
            with compiletools.filesystem_utils.atomic_output_file(
                self.args.makefilename, mode="w", encoding="utf-8"
            ) as f:
                self._write_makefile(graph, f)

    def _write_makefile(self, graph: BuildGraph, f) -> None:
        f.write(f"# Makefile generated by {self.args}\n\n")
        f.write(".DELETE_ON_ERROR:\n\n")
        for rule in graph.rules:
            if rule.rule_type == "phony":
                f.write(f".PHONY: {rule.output}\n")
            line = f"{rule.output}: {' '.join(rule.inputs)}"
            if rule.order_only_deps:
                line += f" | {' '.join(rule.order_only_deps)}"
            f.write(line + "\n")
            if rule.command:
                f.write("\t" + " ".join(rule.command) + "\n")
            f.write("\n")

    def execute(self, target: str = "build") -> None:
        """Run GNU make."""
        import subprocess

        cmd = ["make"]
        if self.args.verbose <= 1:
            cmd.append("-s")
        cmd.extend(["-j", str(getattr(self.args, "parallel", 1))])
        cmd.extend(["-f", self.args.makefilename, target])
        if self.args.verbose >= 1:
            print(" ".join(cmd))
        subprocess.check_call(cmd, universal_newlines=True)
