"""Ninja backend — generates build.ninja files from a BuildGraph."""

from __future__ import annotations

import subprocess

import compiletools.filesystem_utils
from compiletools.build_backend import (
    BuildBackend,
    register_backend,
)
from compiletools.build_graph import BuildGraph


@register_backend
class NinjaBackend(BuildBackend):
    """Generate and execute Ninja build files."""

    @staticmethod
    def name() -> str:
        return "ninja"

    @staticmethod
    def build_filename() -> str:
        return "build.ninja"

    def generate(self, graph: BuildGraph, output=None) -> None:
        self._setup_file_locking()
        graph = self._apply_build_only_changed(graph)

        if output is not None:
            self._write_ninja(graph, output)
        else:
            filename = getattr(self.args, "ninja_filename", "build.ninja")
            with compiletools.filesystem_utils.atomic_output_file(filename, mode="w", encoding="utf-8") as f:
                self._write_ninja(graph, f)

    def _write_ninja(self, graph: BuildGraph, f) -> None:
        f.write("# build.ninja generated by compiletools\n\n")

        rule_types_seen = set()
        for rule in graph.rules:
            if rule.command and rule.rule_type not in rule_types_seen:
                ninja_rule = f"{rule.rule_type}_cmd"
                f.write(f"rule {ninja_rule}\n")
                f.write("  command = $cmd\n")
                if rule.rule_type == "compile":
                    f.write("  description = Compiling $out\n")
                    f.write("  depfile = $out.d\n")
                    f.write("  deps = gcc\n")
                elif rule.rule_type == "link":
                    f.write("  description = Linking $out\n")
                elif rule.rule_type == "static_library":
                    f.write("  description = Archiving $out\n")
                elif rule.rule_type == "shared_library":
                    f.write("  description = Linking shared library $out\n")
                else:
                    f.write(f"  description = {rule.rule_type} $out\n")
                f.write("  restat = 1\n")
                f.write("\n")
                rule_types_seen.add(rule.rule_type)

        for rule in graph.rules:
            if rule.rule_type == "phony":
                f.write(f"build {rule.output}: phony {' '.join(rule.inputs)}\n")
            elif rule.command:
                ninja_rule = f"{rule.rule_type}_cmd"
                # First input is the primary source, rest are implicit deps
                primary = rule.inputs[0] if rule.inputs else ""
                implicit = rule.inputs[1:] if len(rule.inputs) > 1 else []
                line = f"build {rule.output}: {ninja_rule} {primary}"
                if implicit:
                    line += f" | {' '.join(implicit)}"
                if rule.order_only_deps:
                    line += f" || {' '.join(rule.order_only_deps)}"
                f.write(line + "\n")

                if rule.rule_type == "compile":
                    cmd_str = self._wrap_compile_cmd(
                        rule.command + ["-MMD", "-MF", rule.output + ".d"]
                    )
                else:
                    cmd_str = " ".join(rule.command)
                f.write(f"  cmd = {cmd_str}\n")
            f.write("\n")

    def _execute_build(self, target: str) -> None:
        filename = getattr(self.args, "ninja_filename", "build.ninja")
        cmd = ["ninja", "-f", filename]
        parallel = getattr(self.args, "parallel", None)
        if parallel:
            cmd.extend(["-j", str(parallel)])
        if self.args.verbose >= 1:
            cmd.append("-v")
        cmd.append(target)
        subprocess.check_call(cmd, text=True)
