"""Unit tests for the CMake build backend (no compiler required)."""

import io
import os
import shutil
import subprocess
from unittest.mock import MagicMock, patch

import pytest

import compiletools.testhelper as uth
from compiletools.build_backend import extract_copts, extract_linkopts, get_backend_class
from compiletools.build_graph import BuildGraph, BuildRule
from compiletools.cmake_backend import CMakeBackend, _cmake_quote, _filter_x_lang_copts, _separate_include_dirs


class TestCMakeBackendRegistered:
    def test_registered_as_cmake(self):
        cls = get_backend_class("cmake")
        assert cls is CMakeBackend

    def test_name(self):
        assert CMakeBackend.name() == "cmake"

    def test_build_filename(self):
        assert CMakeBackend.build_filename() == "CMakeLists.txt"


class TestCMakeGenerate:
    def _make_backend(self):
        args = MagicMock()
        hunter = MagicMock()
        return CMakeBackend(args=args, hunter=hunter)

    def _generate(self, graph):
        """Build a CMakeBackend, run generate on *graph*, return content."""
        backend = self._make_backend()
        buf = io.StringIO()
        backend.generate(graph, output=buf)
        return buf.getvalue()

    def test_header_comment(self):
        graph = BuildGraph()
        content = self._generate(graph)

        assert "CMakeLists.txt generated by compiletools" in content

    def test_cmake_minimum_required(self):
        graph = BuildGraph()
        content = self._generate(graph)

        assert "cmake_minimum_required(VERSION 3.15)" in content

    def test_project_declaration(self):
        graph = BuildGraph()
        content = self._generate(graph)

        assert "project(compiletools_build CXX)" in content

    def test_single_source_executable(self):
        graph = BuildGraph()
        graph.add_rule(
            BuildRule(
                output="obj/hello.o",
                inputs=["hello.cpp"],
                command=["g++", "-O2", "-c", "hello.cpp", "-o", "obj/hello.o"],
                rule_type="compile",
            )
        )
        graph.add_rule(
            BuildRule(
                output="bin/hello",
                inputs=["obj/hello.o"],
                command=["g++", "-o", "bin/hello", "obj/hello.o"],
                rule_type="link",
            )
        )

        content = self._generate(graph)

        assert "add_executable(hello" in content
        assert "hello.cpp" in content

    def test_multiple_sources(self):
        graph = BuildGraph()
        graph.add_rule(
            BuildRule(
                output="obj/main.o",
                inputs=["main.cpp"],
                command=["g++", "-c", "main.cpp", "-o", "obj/main.o"],
                rule_type="compile",
            )
        )
        graph.add_rule(
            BuildRule(
                output="obj/util.o",
                inputs=["util.cpp", "util.h"],
                command=["g++", "-c", "util.cpp", "-o", "obj/util.o"],
                rule_type="compile",
            )
        )
        graph.add_rule(
            BuildRule(
                output="bin/app",
                inputs=["obj/main.o", "obj/util.o"],
                command=["g++", "-o", "bin/app", "obj/main.o", "obj/util.o"],
                rule_type="link",
            )
        )

        content = self._generate(graph)

        assert "add_executable(app" in content
        assert "main.cpp" in content
        assert "util.cpp" in content
        assert "util.h" in content

    def test_compile_options(self):
        graph = BuildGraph()
        graph.add_rule(
            BuildRule(
                output="obj/foo.o",
                inputs=["foo.cpp"],
                command=["g++", "-O2", "-std=c++17", "-DFOO=1", "-c", "foo.cpp", "-o", "obj/foo.o"],
                rule_type="compile",
            )
        )
        graph.add_rule(
            BuildRule(
                output="bin/foo",
                inputs=["obj/foo.o"],
                command=["g++", "-o", "bin/foo", "obj/foo.o"],
                rule_type="link",
            )
        )

        content = self._generate(graph)

        assert "target_compile_options(foo PRIVATE" in content
        assert '"-O2"' in content
        assert '"-std=c++17"' in content
        assert '"-DFOO=1"' in content

    def test_link_options(self):
        graph = BuildGraph()
        graph.add_rule(
            BuildRule(
                output="obj/foo.o",
                inputs=["foo.cpp"],
                command=["g++", "-c", "foo.cpp", "-o", "obj/foo.o"],
                rule_type="compile",
            )
        )
        graph.add_rule(
            BuildRule(
                output="bin/foo",
                inputs=["obj/foo.o"],
                command=["g++", "-o", "bin/foo", "obj/foo.o", "-lm", "-lpthread"],
                rule_type="link",
            )
        )

        content = self._generate(graph)

        assert "target_link_libraries(foo PRIVATE" in content
        assert '"m"' in content
        assert '"pthread"' in content

    def test_include_dirs_separated(self):
        graph = BuildGraph()
        graph.add_rule(
            BuildRule(
                output="obj/foo.o",
                inputs=["foo.cpp"],
                command=["g++", "-I/usr/include", "-I/opt/local/include", "-Wall", "-c", "foo.cpp", "-o", "obj/foo.o"],
                rule_type="compile",
            )
        )
        graph.add_rule(
            BuildRule(
                output="bin/foo",
                inputs=["obj/foo.o"],
                command=["g++", "-o", "bin/foo", "obj/foo.o"],
                rule_type="link",
            )
        )

        content = self._generate(graph)

        assert "target_include_directories(foo PRIVATE" in content
        assert '"/usr/include"' in content
        assert '"/opt/local/include"' in content
        # -Wall should be in compile_options, not include_directories
        assert "target_compile_options(foo PRIVATE" in content
        assert '"-Wall"' in content

    def test_empty_graph(self):
        graph = BuildGraph()
        content = self._generate(graph)

        assert "cmake_minimum_required" in content
        assert "add_executable" not in content

    def test_phony_rules_not_emitted(self):
        graph = BuildGraph()
        graph.add_rule(BuildRule(output="build", inputs=["bin/foo"], command=None, rule_type="phony"))
        graph.add_rule(BuildRule(output="all", inputs=["build"], command=None, rule_type="phony"))

        content = self._generate(graph)

        assert "add_executable" not in content
        assert "phony" not in content

    def test_headers_in_sources(self):
        graph = BuildGraph()
        graph.add_rule(
            BuildRule(
                output="obj/main.o",
                inputs=["main.cpp", "config.h", "types.h"],
                command=["g++", "-c", "main.cpp", "-o", "obj/main.o"],
                rule_type="compile",
            )
        )
        graph.add_rule(
            BuildRule(
                output="bin/main",
                inputs=["obj/main.o"],
                command=["g++", "-o", "bin/main", "obj/main.o"],
                rule_type="link",
            )
        )

        content = self._generate(graph)

        assert "config.h" in content
        assert "types.h" in content

    def test_emits_custom_command_per_test(self):
        """Each RuleType.TEST rule becomes an add_custom_command that runs the
        freshly built binary via $<TARGET_FILE:...> and touches its .result
        marker, gathered under a ``runtests ALL`` target — no ctest."""
        graph = BuildGraph()
        graph.add_rule(
            BuildRule(
                output="obj/test_foo.o",
                inputs=["test_foo.cpp"],
                command=["g++", "-c", "test_foo.cpp", "-o", "obj/test_foo.o"],
                rule_type="compile",
            )
        )
        graph.add_rule(
            BuildRule(
                output="bin/test_foo",
                inputs=["obj/test_foo.o"],
                command=["g++", "-o", "bin/test_foo", "obj/test_foo.o"],
                rule_type="link",
            )
        )
        graph.add_rule(
            BuildRule(
                output="bin/test_foo.result",
                inputs=["bin/test_foo"],
                command=["bin/test_foo"],
                rule_type="test",
                success_marker="bin/test_foo.result",
            )
        )

        content = self._generate(graph)

        assert "add_custom_command(" in content
        # Graph paths are anchored to ${CMAKE_SOURCE_DIR}: add_custom_command
        # resolves a relative OUTPUT against the build dir, not the source
        # tree, which would bury the .result marker inside cmake-build/.
        assert 'OUTPUT "${CMAKE_SOURCE_DIR}/bin/test_foo.result"' in content
        assert '-E touch "${CMAKE_SOURCE_DIR}/bin/test_foo.result"' in content
        assert "$<TARGET_FILE:test_foo>" in content
        assert "DEPENDS test_foo" in content
        assert 'add_custom_target(runtests ALL DEPENDS "${CMAKE_SOURCE_DIR}/bin/test_foo.result")' in content
        # ctest is no longer involved.
        assert "enable_testing" not in content
        assert "add_test(" not in content


class TestCmakeQuote:
    """``_cmake_quote`` must produce well-formed CMake quoted arguments.

    Tokens are wrapped in ``"..."`` with any embedded ``"`` escaped as ``\\"``
    so that cmake's Makefile generator passes them verbatim to the compiler.
    The specific bug: ``f'"{c}"'`` for ``c = '-DFOO="bar"'`` produced the
    malformed cmake syntax ``"-DFOO="bar""``; the helper fixes that.
    """

    def test_plain_flag_unchanged(self):
        assert _cmake_quote("-O2") == '"-O2"'

    def test_define_without_quotes(self):
        assert _cmake_quote("-DFOO=1") == '"-DFOO=1"'

    def test_flag_with_embedded_double_quotes(self):
        # -DCT_PROJECT_VERSION="1.2.3" must survive cmake quoting so the
        # macro expands to a C string literal, not a bare number.
        result = _cmake_quote('-DCT_PROJECT_VERSION="1.2.3"')
        # Outer quotes + inner " escaped as \":
        assert result == '"-DCT_PROJECT_VERSION=\\"1.2.3\\""'
        # The malformed form (pre-fix) must not be produced.
        assert result != '"-DCT_PROJECT_VERSION="1.2.3""'

    def test_flag_with_string_value_name(self):
        assert _cmake_quote('-DCT_PROJECT_NAME="demo_app"') == '"-DCT_PROJECT_NAME=\\"demo_app\\""'

    def test_backslash_escaped(self):
        # A backslash in a token is escaped so cmake does not treat it as
        # the start of an escape sequence inside a quoted arg.
        result = _cmake_quote("-DPATH=a\\b")
        assert result == '"-DPATH=a\\\\b"'


class TestSeparateIncludeDirs:
    def test_separates_i_flags(self):
        copts = ["-I/usr/include", "-O2", "-I/opt/include", "-Wall"]
        dirs, remaining = _separate_include_dirs(copts)
        assert dirs == ["/usr/include", "/opt/include"]
        assert remaining == ["-O2", "-Wall"]

    def test_no_i_flags(self):
        copts = ["-O2", "-Wall"]
        dirs, remaining = _separate_include_dirs(copts)
        assert dirs == []
        assert remaining == ["-O2", "-Wall"]

    def test_empty(self):
        dirs, remaining = _separate_include_dirs([])
        assert dirs == []
        assert remaining == []

    def test_only_i_flags(self):
        copts = ["-I/a", "-I/b"]
        dirs, remaining = _separate_include_dirs(copts)
        assert dirs == ["/a", "/b"]
        assert remaining == []


class TestCoptsExtraction:
    def test_basic_flags(self):
        cmd = ["g++", "-O2", "-std=c++17", "-c", "foo.cpp", "-o", "obj/foo.o"]
        assert extract_copts(cmd) == ["-O2", "-std=c++17"]

    def test_empty_command(self):
        assert extract_copts([]) == []


class TestLinkoptsExtraction:
    def test_library_flags(self):
        cmd = ["g++", "-o", "bin/foo", "obj/foo.o", "-lm", "-lpthread"]
        objs = {"obj/foo.o"}
        assert extract_linkopts(cmd, objs) == ["-lm", "-lpthread"]

    def test_empty_command(self):
        assert extract_linkopts([], set()) == []


class TestCMakeExecute:
    def test_raises_when_cmake_not_found(self):
        args = MagicMock()
        hunter = MagicMock()
        backend = CMakeBackend(args=args, hunter=hunter)

        with patch("shutil.which", return_value=None):
            with pytest.raises(RuntimeError, match=r"cmake.*not found"):
                backend.execute()

    def _capture_configure(self, *, CXX, CC, tmp_path, cmakelists_dir=None):
        """Run _execute_build('build') with subprocess and FS calls stubbed,
        returning the configure command list."""
        import os

        args = MagicMock()
        args.CXX = CXX
        args.CC = CC
        args.cas_objdir = str(tmp_path / "obj")
        args.parallel = 0
        args.output = str(tmp_path / "out")
        os.makedirs(args.cas_objdir, exist_ok=True)

        hunter = MagicMock()
        backend = CMakeBackend(args=args, hunter=hunter)
        backend._graph = None

        captured = []

        def fake_check_call(cmd, **kwargs):
            captured.append(cmd)

        cmakelists_dir = cmakelists_dir if cmakelists_dir is not None else tmp_path
        os.makedirs(cmakelists_dir, exist_ok=True)
        cmakelists_path = str(os.path.join(cmakelists_dir, "CMakeLists.txt"))

        with (
            patch("shutil.which", return_value="/usr/bin/cmake"),
            patch("subprocess.check_call", side_effect=fake_check_call),
            patch.object(backend, "_copy_built_executables"),
            patch.object(backend, "build_filename", return_value=cmakelists_path),
        ):
            with open(cmakelists_path, "w") as fh:
                fh.write("")
            backend._execute_build("build")

        # First call is configure
        return captured[0]

    def test_configure_with_plain_compiler(self, tmp_path):
        """Without a wrapper, CMAKE_CXX_COMPILER gets the bare compiler and
        no LAUNCHER variable is emitted."""
        cmd = self._capture_configure(CXX="g++", CC="gcc", tmp_path=tmp_path)

        assert "-DCMAKE_CXX_COMPILER=g++" in cmd
        assert "-DCMAKE_C_COMPILER=gcc" in cmd
        assert not any(a.startswith("-DCMAKE_CXX_COMPILER_LAUNCHER=") for a in cmd)
        assert not any(a.startswith("-DCMAKE_C_COMPILER_LAUNCHER=") for a in cmd)

    def test_build_dir_differs_per_source_dir(self, tmp_path):
        """Two source trees sharing one cas_objdir must NOT collide on
        ``cmake-build/`` — CMake binds CMakeCache.txt to one source dir, so
        a shared build_dir produces ``CMake Error: The source ... does not
        match the source ... used to generate cache.`` Build dir must be
        keyed by source dir.

        ``tmp_path`` is not under a real git checkout, so this exercises the
        absolute-source-dir fallback (no real ``.git`` → no anchoring). The
        gitroot-anchored variant is exercised by
        ``test_build_dir_differs_per_gitroot``."""
        src_a = tmp_path / "proj_a"
        src_b = tmp_path / "proj_b"
        cmd_a = self._capture_configure(CXX="g++", CC="gcc", tmp_path=tmp_path, cmakelists_dir=src_a)
        cmd_b = self._capture_configure(CXX="g++", CC="gcc", tmp_path=tmp_path, cmakelists_dir=src_b)

        # Extract the -B argument (build dir) from each configure command
        def build_dir_of(cmd):
            i = cmd.index("-B")
            return cmd[i + 1]

        bd_a = build_dir_of(cmd_a)
        bd_b = build_dir_of(cmd_b)
        assert bd_a != bd_b, f"build_dir must differ per source dir; got {bd_a!r} == {bd_b!r}"
        # Both must live inside cas_objdir
        assert bd_a.startswith(str(tmp_path / "obj"))
        assert bd_b.startswith(str(tmp_path / "obj"))
        # Sanity: same source dir twice → same build_dir (deterministic hash)
        cmd_a2 = self._capture_configure(CXX="g++", CC="gcc", tmp_path=tmp_path, cmakelists_dir=src_a)
        assert build_dir_of(cmd_a2) == bd_a

    def test_build_dir_differs_per_gitroot(self, tmp_path):
        """Inside real git checkouts, the build_dir hash key is
        ``(gitroot_basename | gitroot-relative source dir)`` — workspace
        invariant, so two checkouts of the same project at different
        absolute paths collide (deliberately, to preserve cross-workspace
        ``.o`` byte-identity under shared ``cas_objdir``), but two
        distinct gitroot-name projects sharing a ``cas_objdir`` get
        distinct build dirs."""
        # Two checkouts of "same" project at different abs paths.
        alice = tmp_path / "alice" / "proj"
        bob = tmp_path / "bob" / "proj"
        # Two unrelated projects sharing a cas_objdir.
        other = tmp_path / "alice" / "other"
        # Real git markers: `.git` directory containing HEAD (so
        # `find_git_root`'s fallback walker accepts each as a genuine
        # repository, not a fake/empty placeholder).
        import compiletools.git_utils as _gu

        _gu.clear_cache()
        for d in (alice, bob, other):
            d.mkdir(parents=True)
            git_dir = d / ".git"
            git_dir.mkdir()
            (git_dir / "HEAD").write_text("ref: refs/heads/main\n")

        def build_dir_of(cmd):
            return cmd[cmd.index("-B") + 1]

        cmd_alice = self._capture_configure(CXX="g++", CC="gcc", tmp_path=tmp_path, cmakelists_dir=alice)
        cmd_bob = self._capture_configure(CXX="g++", CC="gcc", tmp_path=tmp_path, cmakelists_dir=bob)
        cmd_other = self._capture_configure(CXX="g++", CC="gcc", tmp_path=tmp_path, cmakelists_dir=other)

        bd_alice = build_dir_of(cmd_alice)
        bd_bob = build_dir_of(cmd_bob)
        bd_other = build_dir_of(cmd_other)

        # Two checkouts of same-named project → same build_dir (workspace-invariant key)
        assert bd_alice == bd_bob, (
            f"two checkouts of same project should hash identically; got {bd_alice!r} vs {bd_bob!r}"
        )
        # Different gitroot basename → different build_dir
        assert bd_alice != bd_other, (
            f"unrelated projects must NOT collide on cmake-build; got {bd_alice!r} == {bd_other!r}"
        )

    def test_build_dir_stable_across_cwd_changes(self, tmp_path, monkeypatch):
        """build_filename() may be a bare ``CMakeLists.txt`` (relative). The
        cache key must NOT depend on the process's cwd at the moment
        ``_execute_build`` runs.

        Two *different logical projects* are invoked from cwds where the same
        bare relative filename ``CMakeLists.txt`` resolves to each one. Without
        the ``abspath`` fix the *cached* ``wrappedos.realpath('CMakeLists.txt')``
        result from the first call (keyed on the input string) is reused for
        the second call, collapsing both projects to the same build dir — a
        cross-project collision under shared ``cas_objdir``. With the fix,
        ``abspath`` runs first (cwd-resolved lexically) so two distinct cwds
        feed distinct *absolute* strings into ``wrappedos.realpath`` and the
        per-project answers stay distinct."""
        import compiletools.git_utils as _gu
        import compiletools.wrappedos as _wos

        # Two independent projects, each with its own real .git marker.
        proj_a = tmp_path / "proj_a"
        proj_b = tmp_path / "proj_b"
        for d in (proj_a, proj_b):
            d.mkdir()
            (d / ".git").mkdir()
            (d / ".git" / "HEAD").write_text("ref: refs/heads/main\n")
            (d / "CMakeLists.txt").write_text("")
        # NB: only clear once before the pair so the second call inherits any
        # poisoned wrappedos cache from the first — reproducing the bug.
        _gu.clear_cache()
        _wos.clear_cache()

        def build_dir(cwd):
            args = MagicMock()
            args.CXX = "g++"
            args.CC = "gcc"
            args.cas_objdir = str(tmp_path / "obj")
            args.parallel = 0
            args.output = str(tmp_path / "out")
            os.makedirs(args.cas_objdir, exist_ok=True)
            hunter = MagicMock()
            backend = CMakeBackend(args=args, hunter=hunter)
            backend._graph = None
            captured = []
            monkeypatch.chdir(cwd)
            with (
                patch("shutil.which", return_value="/usr/bin/cmake"),
                patch("subprocess.check_call", side_effect=lambda cmd, **kw: captured.append(cmd)),
                patch.object(backend, "_copy_built_executables"),
                # Bare relative filename — the load-bearing piece. realpath()'s
                # functools.cache keys on the string, so a second call from a
                # different cwd returns the stale answer without abspath first.
                patch.object(backend, "build_filename", return_value="CMakeLists.txt"),
            ):
                backend._execute_build("build")
            return captured[0][captured[0].index("-B") + 1]

        bd_a = build_dir(proj_a)
        bd_b = build_dir(proj_b)
        assert bd_a != bd_b, (
            f"two distinct projects must hash to different build_dirs even when invoked with the "
            f"same bare relative build_filename from different cwds; got {bd_a!r} == {bd_b!r}"
        )

    def test_build_dir_blake2b_pinned_for_known_input(self, tmp_path):
        """Regression guard: pin the hash output for a known input so that a
        future swap of the hashing algorithm (or its truncation width) is
        caught by the test suite. Mirrors the production keying path:
        blake2b(<gitroot_name>|<rel_src>, digest_size=6).hexdigest()."""
        import hashlib

        key_material = "myproj|."
        expected = hashlib.blake2b(key_material.encode("utf-8"), digest_size=6).hexdigest()
        # Exactly 12 hex chars (6 bytes * 2) — width invariant the cmake_backend
        # cache directory layout depends on.
        assert len(expected) == 12

        # End-to-end check that the build_dir suffix matches what the keying
        # function produces for the literal "myproj" project at the gitroot.
        import compiletools.git_utils as _gu

        proj = tmp_path / "myproj"
        proj.mkdir()
        (proj / ".git").mkdir()
        (proj / ".git" / "HEAD").write_text("ref: refs/heads/main\n")
        (proj / "CMakeLists.txt").write_text("")
        _gu.clear_cache()

        args = MagicMock()
        args.CXX = "g++"
        args.CC = "gcc"
        args.cas_objdir = str(tmp_path / "obj")
        args.parallel = 0
        args.output = str(tmp_path / "out")
        os.makedirs(args.cas_objdir, exist_ok=True)
        hunter = MagicMock()
        backend = CMakeBackend(args=args, hunter=hunter)
        backend._graph = None
        captured = []
        with (
            patch("shutil.which", return_value="/usr/bin/cmake"),
            patch("subprocess.check_call", side_effect=lambda cmd, **kw: captured.append(cmd)),
            patch.object(backend, "_copy_built_executables"),
            patch.object(backend, "build_filename", return_value=str(proj / "CMakeLists.txt")),
        ):
            backend._execute_build("build")
        bd = captured[0][captured[0].index("-B") + 1]
        assert bd.endswith(f"cmake-build-{expected}"), f"expected suffix cmake-build-{expected}; got {bd!r}"

    def test_build_dir_falls_back_when_source_not_under_gitroot(self, tmp_path):
        """If the resolved ``source_dir`` is not actually under the gitroot
        ``anchor_real`` (symlink, separate tree, race), ``os.path.relpath``
        would emit ``../../...`` traversal escapes that leak absolute
        workspace structure into the key. The fix is to detect this case
        and fall back to hashing the absolute source dir directly."""
        import hashlib

        import compiletools.git_utils as _gu

        # Real gitroot in one location.
        gitroot = tmp_path / "real_root"
        gitroot.mkdir()
        (gitroot / ".git").mkdir()
        (gitroot / ".git" / "HEAD").write_text("ref: refs/heads/main\n")
        # Source dir lives in a completely separate tree.
        outside_src = tmp_path / "outside" / "proj"
        outside_src.mkdir(parents=True)
        (outside_src / "CMakeLists.txt").write_text("")
        _gu.clear_cache()

        args = MagicMock()
        args.CXX = "g++"
        args.CC = "gcc"
        args.cas_objdir = str(tmp_path / "obj")
        args.parallel = 0
        args.output = str(tmp_path / "out")
        os.makedirs(args.cas_objdir, exist_ok=True)
        hunter = MagicMock()
        backend = CMakeBackend(args=args, hunter=hunter)
        backend._graph = None
        captured = []
        # Force find_git_root to return the unrelated gitroot, simulating a
        # build where the resolved source dir doesn't live under it.
        with (
            patch("shutil.which", return_value="/usr/bin/cmake"),
            patch("subprocess.check_call", side_effect=lambda cmd, **kw: captured.append(cmd)),
            patch.object(backend, "_copy_built_executables"),
            patch.object(backend, "build_filename", return_value=str(outside_src / "CMakeLists.txt")),
            patch("compiletools.git_utils.find_git_root", return_value=str(gitroot)),
        ):
            backend._execute_build("build")
        bd = captured[0][captured[0].index("-B") + 1]
        # Expect the absolute-path fallback hash, NOT a hash containing
        # traversal escapes ("../../..").
        expected_key = hashlib.blake2b(str(outside_src).encode("utf-8"), digest_size=6).hexdigest()
        assert bd.endswith(f"cmake-build-{expected_key}"), (
            f"expected fallback to absolute-path hash {expected_key!r}; got {bd!r}"
        )

    def test_build_dir_handles_root_gitroot(self, tmp_path):
        """``anchor_real == '/'`` would basename to ``''`` and produce a key
        like ``|rel`` with an empty gitroot name. Substitute a sentinel
        (``ROOT``) so the key always has a nonempty gitroot name."""
        import hashlib

        import compiletools.git_utils as _gu

        # We can't actually make a gitroot at "/", but we can simulate it.
        src = tmp_path / "src"
        src.mkdir()
        (src / "CMakeLists.txt").write_text("")
        _gu.clear_cache()

        args = MagicMock()
        args.CXX = "g++"
        args.CC = "gcc"
        args.cas_objdir = str(tmp_path / "obj")
        args.parallel = 0
        args.output = str(tmp_path / "out")
        os.makedirs(args.cas_objdir, exist_ok=True)
        hunter = MagicMock()
        backend = CMakeBackend(args=args, hunter=hunter)
        backend._graph = None
        captured = []

        # Patch is_real_git_marker → True for "/", and realpath("/") → "/".
        with (
            patch("shutil.which", return_value="/usr/bin/cmake"),
            patch("subprocess.check_call", side_effect=lambda cmd, **kw: captured.append(cmd)),
            patch.object(backend, "_copy_built_executables"),
            patch.object(backend, "build_filename", return_value=str(src / "CMakeLists.txt")),
            patch("compiletools.git_utils.find_git_root", return_value="/"),
            patch("compiletools.git_utils.is_real_git_marker", return_value=True),
        ):
            backend._execute_build("build")
        bd = captured[0][captured[0].index("-B") + 1]
        rel_src = os.path.relpath(str(src), "/")
        expected_key = hashlib.blake2b(f"ROOT|{rel_src}".encode(), digest_size=6).hexdigest()
        assert bd.endswith(f"cmake-build-{expected_key}"), f"expected sentinel-ROOT key {expected_key!r}; got {bd!r}"

    def test_configure_with_ccache_wrapper(self, tmp_path):
        """``CXX='ccache g++'`` must split into COMPILER + COMPILER_LAUNCHER —
        passing the literal string to -DCMAKE_CXX_COMPILER would fail because
        CMake expects a single executable path."""
        cmd = self._capture_configure(CXX="ccache g++", CC="ccache gcc", tmp_path=tmp_path)

        assert "-DCMAKE_CXX_COMPILER=g++" in cmd, f"Expected bare compiler in CMAKE_CXX_COMPILER; got {cmd}"
        assert "-DCMAKE_C_COMPILER=gcc" in cmd, f"Expected bare compiler in CMAKE_C_COMPILER; got {cmd}"
        assert "-DCMAKE_CXX_COMPILER_LAUNCHER=ccache" in cmd, (
            f"Expected wrapper in CMAKE_CXX_COMPILER_LAUNCHER; got {cmd}"
        )
        assert "-DCMAKE_C_COMPILER_LAUNCHER=ccache" in cmd, f"Expected wrapper in CMAKE_C_COMPILER_LAUNCHER; got {cmd}"
        # The literal "ccache g++" must never appear as an argument value
        assert not any("ccache g++" in a for a in cmd), (
            f"CMake compiler argument still contains the literal wrapped string: {cmd}"
        )


class TestCMakeAllOutputsCurrent:
    """CMake backends place outputs in cmake-build/, not at namer paths,
    so the base-class _all_outputs_current pre-check would mis-fire.
    The override must return False unconditionally so the build (and
    post-build copy) always runs."""

    def test_always_returns_false_even_when_outputs_exist(self, tmp_path):
        args = MagicMock()
        hunter = MagicMock()
        backend = CMakeBackend(args=args, hunter=hunter)

        # Build a graph whose compile/link outputs exist on disk and have
        # matching link signatures — base class would return True.
        from compiletools.build_backend import compute_link_signature

        obj_path = str(tmp_path / "foo.o")
        exe_path = str(tmp_path / "main")
        with open(obj_path, "w") as f:
            f.write("object")
        with open(exe_path, "w") as f:
            f.write("executable")

        graph = BuildGraph()
        graph.add_rule(BuildRule(output=obj_path, inputs=["foo.cpp"], command=["g++"], rule_type="compile"))
        link_rule = BuildRule(
            output=exe_path, inputs=[obj_path], command=["g++", "-o", exe_path, obj_path], rule_type="link"
        )
        graph.add_rule(link_rule)
        with open(exe_path + ".ct-sig", "w") as f:
            f.write(compute_link_signature(link_rule))

        # CMake override must still return False — defer to CMake.
        assert backend._all_outputs_current(graph) is False

    def test_always_returns_false_with_empty_graph(self):
        args = MagicMock()
        hunter = MagicMock()
        backend = CMakeBackend(args=args, hunter=hunter)
        assert backend._all_outputs_current(BuildGraph()) is False


class TestFilterXLangCopts:
    """Unit tests for _filter_x_lang_copts helper."""

    def test_removes_orphan_x_flag(self):
        # extract_copts produces an orphan -x (c++ argument is dropped)
        copts = ["-std=c++20", "-fmodules-ts", "-x"]
        assert _filter_x_lang_copts(copts) == ["-std=c++20", "-fmodules-ts"]

    def test_removes_x_with_paired_lang_arg(self):
        # If somehow -x c++ appears as two elements
        copts = ["-std=c++20", "-x", "c++", "-fmodules-ts"]
        assert _filter_x_lang_copts(copts) == ["-std=c++20", "-fmodules-ts"]

    def test_no_x_flag_unchanged(self):
        copts = ["-std=c++20", "-O2", "-Wall"]
        assert _filter_x_lang_copts(copts) == ["-std=c++20", "-O2", "-Wall"]

    def test_empty(self):
        assert _filter_x_lang_copts([]) == []

    def test_x_flag_at_end_removed(self):
        copts = ["-O2", "-x"]
        assert _filter_x_lang_copts(copts) == ["-O2"]

    def test_x_followed_by_flag_token_preserved(self):
        """`-x` followed by a flag-shaped token (e.g., `-Wall`) should
        only strip `-x`; the flag token is NOT a language argument."""
        assert _filter_x_lang_copts(["-x", "-Wall"]) == ["-Wall"]


class TestCppmPerSourceProperties:
    """Test that .cppm sources get per-source set_source_files_properties and
    -x is NOT in global target_compile_options.

    Background: gcc injects ``-x c++`` immediately before the .cppm filename
    so it recognises the extension as C++ source.  build_backend.extract_copts
    keeps the orphan ``-x`` (``c++`` is not flag-shaped) and aggregate_rule_sources
    deduplicates it into all_copts.  cmake's target_compile_options then emits
    that orphan at global scope; gcc interprets the next token (cmake's own
    ``-MD``) as the language argument and raises:
        g++: error: language -MD not recognized
    Fix: filter ``-x`` from global copts, emit per-source
    set_source_files_properties for each .cppm file.
    """

    def _make_backend(self):
        args = MagicMock()
        hunter = MagicMock()
        return CMakeBackend(args=args, hunter=hunter)

    def _generate(self, graph):
        """Build a CMakeBackend, run generate on *graph*, return content."""
        backend = self._make_backend()
        buf = io.StringIO()
        backend.generate(graph, output=buf)
        return buf.getvalue()

    def _build_graph_with_cppm(self, cppm_path: str = "math.cppm") -> BuildGraph:
        """Return a minimal BuildGraph: one .cppm compile + one link rule."""
        graph = BuildGraph()
        # The compile command mirrors what build_backend._create_compile_rule emits
        # for a gcc .cppm file: -x c++ placed immediately before the filename.
        graph.add_rule(
            BuildRule(
                output="obj/math.o",
                inputs=[cppm_path],
                command=[
                    "g++",
                    "-std=c++20",
                    "-fmodules-ts",
                    "-c",
                    "-x",
                    "c++",
                    cppm_path,
                    "-o",
                    "obj/math.o",
                ],
                rule_type="compile",
            )
        )
        graph.add_rule(
            BuildRule(
                output="bin/math",
                inputs=["obj/math.o"],
                command=["g++", "-o", "bin/math", "obj/math.o"],
                rule_type="link",
            )
        )
        return graph

    def test_cppm_has_per_source_compile_options(self):
        """set_source_files_properties must appear for the .cppm source."""
        graph = self._build_graph_with_cppm("math.cppm")
        content = self._generate(graph)

        assert "set_source_files_properties" in content
        assert "math.cppm" in content
        # The per-source block must contain COMPILE_OPTIONS and LANGUAGE CXX
        assert "COMPILE_OPTIONS" in content
        assert "LANGUAGE CXX" in content

    def test_cppm_per_source_contains_x_cxx(self):
        """The per-source COMPILE_OPTIONS must encode -x;c++ (cmake list separator)."""
        graph = self._build_graph_with_cppm("math.cppm")
        content = self._generate(graph)

        # Check that -x and c++ appear in the set_source_files_properties block
        lines = content.splitlines()
        ssf_lines = [ln for ln in lines if "set_source_files_properties" in ln or "COMPILE_OPTIONS" in ln]
        combined = "\n".join(ssf_lines)
        assert "-x" in combined
        assert "c++" in combined

    def test_global_target_compile_options_no_x_flag(self):
        """The orphan -x must NOT appear in global target_compile_options."""
        graph = self._build_graph_with_cppm("math.cppm")
        content = self._generate(graph)

        lines = content.splitlines()
        tco_lines = [ln for ln in lines if "target_compile_options" in ln]
        for ln in tco_lines:
            assert '"-x"' not in ln, f"Orphan -x found in global target_compile_options: {ln!r}"

    def test_regular_cpp_no_per_source_properties(self):
        """Regular .cpp sources must NOT trigger set_source_files_properties."""
        graph = BuildGraph()
        graph.add_rule(
            BuildRule(
                output="obj/main.o",
                inputs=["main.cpp"],
                command=["g++", "-std=c++20", "-c", "main.cpp", "-o", "obj/main.o"],
                rule_type="compile",
            )
        )
        graph.add_rule(
            BuildRule(
                output="bin/main",
                inputs=["obj/main.o"],
                command=["g++", "-o", "bin/main", "obj/main.o"],
                rule_type="link",
            )
        )
        content = self._generate(graph)

        assert "set_source_files_properties" not in content


class TestCMakeNamedModuleIfaceLinkWiring:
    """Named-module interface units (.cppm) are pre-compiled locally by
    ``_prebuild_aux_artefacts`` before cmake runs. They MUST be excluded
    from ``add_executable`` srcs and instead supplied to the linker as
    prebuilt object files.

    Race rationale: the interface compile command writes the BMI (.gcm)
    to a fixed mapper-resolved path inside cas-pcmdir. If cmake re-compiles
    the .cppm file (because it appears in add_executable srcs), the gcc
    invocation truncates and rewrites that .gcm path while a peer importer
    compile in the same cmake --parallel invocation may simultaneously
    open it for reading. Race symptom (observed on CI gcc-14.2.0 / make
    generator): ``math: error: failed to read compiled module: No such
    file or directory``. The prebuild already produced the .o + .gcm;
    cmake must consume them, not re-produce them.
    """

    def _make_backend(self):
        args = MagicMock()
        hunter = MagicMock()
        return CMakeBackend(args=args, hunter=hunter)

    def _build_graph_with_module_iface(self) -> BuildGraph:
        """Importer main.cpp + named-module interface math.cppm linked together."""
        graph = BuildGraph()
        graph.add_rule(
            BuildRule(
                output="/abs/cas-objdir/ab/math_abcd.o",
                inputs=["/abs/ws/math.cppm"],
                command=[
                    "g++",
                    "-std=c++20",
                    "-fmodules-ts",
                    "-c",
                    "-x",
                    "c++",
                    "/abs/ws/math.cppm",
                    "-o",
                    "/abs/cas-objdir/ab/math_abcd.o",
                ],
                rule_type="compile",
            )
        )
        graph.add_rule(
            BuildRule(
                output="/abs/cas-objdir/cd/main_efgh.o",
                inputs=["/abs/ws/main.cpp"],
                command=[
                    "g++",
                    "-std=c++20",
                    "-fmodules-ts",
                    "-c",
                    "/abs/ws/main.cpp",
                    "-o",
                    "/abs/cas-objdir/cd/main_efgh.o",
                ],
                rule_type="compile",
            )
        )
        graph.add_rule(
            BuildRule(
                output="bin/main",
                inputs=["/abs/cas-objdir/ab/math_abcd.o", "/abs/cas-objdir/cd/main_efgh.o"],
                command=["g++", "-o", "bin/main", "/abs/cas-objdir/ab/math_abcd.o", "/abs/cas-objdir/cd/main_efgh.o"],
                rule_type="link",
            )
        )
        return graph

    def test_cppm_not_in_add_executable_srcs(self):
        """The .cppm source must NOT appear in add_executable srcs."""
        graph = self._build_graph_with_module_iface()
        backend = self._make_backend()
        # Mark math.cppm's .o as a named-module interface producer; the
        # backend must keep that .o out of the compile target's srcs.
        backend._module_iface_obj = {"math": "/abs/cas-objdir/ab/math_abcd.o"}
        buf = io.StringIO()
        backend.generate(graph, output=buf)
        content = buf.getvalue()

        # main.cpp is a regular importer, still compiled by cmake.
        assert "/abs/ws/main.cpp" in content
        # math.cppm is a named-module interface — already compiled by the
        # prebuild step; cmake must not list it as a source.
        assert "math.cppm" not in content, (
            "math.cppm leaked into the cmake target srcs; cmake will re-compile "
            "it and race with the prebuild-produced .gcm"
        )

    def test_prebuilt_module_iface_obj_linked_in(self):
        """The prebuilt interface .o must be passed to the linker so the
        module's definitions are present in the final binary."""
        graph = self._build_graph_with_module_iface()
        backend = self._make_backend()
        backend._module_iface_obj = {"math": "/abs/cas-objdir/ab/math_abcd.o"}
        buf = io.StringIO()
        backend.generate(graph, output=buf)
        content = buf.getvalue()

        # The prebuilt .o path must be supplied to the linker. cmake
        # passes absolute paths in target_link_libraries directly to ld.
        assert "/abs/cas-objdir/ab/math_abcd.o" in content, (
            "prebuilt named-module interface .o is not wired into the linker; "
            "the executable would link without the module's definitions and "
            "fail with 'undefined reference'"
        )

    def test_no_module_iface_obj_leaves_graph_unchanged(self):
        """Backends without named-module producers (the common case) must
        keep their previous behaviour: .cppm sources stay in add_executable
        srcs and no spurious prebuilt-object link entries appear."""
        graph = self._build_graph_with_module_iface()
        backend = self._make_backend()
        # Empty _module_iface_obj — no named modules.
        buf = io.StringIO()
        backend.generate(graph, output=buf)
        content = buf.getvalue()

        assert "math.cppm" in content


@pytest.mark.skipif(shutil.which("cmake") is None, reason="cmake not on PATH")
class TestCMakeRunsTestsInBuildPhase:
    """CMakeBackend.execute("build") runs each test via its runtests-target
    add_custom_command, so ``cmake --build`` runs the test as part of the
    build — no separate post-build ``runtests`` phase.
    """

    @pytest.fixture(autouse=True)
    def _reset_parser_state(self):
        uth.reset()
        yield
        uth.reset()

    @pytest.fixture(autouse=True)
    def _chdir_to_tmp(self, monkeypatch, tmp_path):
        monkeypatch.chdir(tmp_path)

    @uth.requires_functional_compiler
    def test_cmake_runs_tests_in_build(self, tmp_path):
        """After execute("build") — NOT execute("runtests") — the test's
        ``.result`` success marker exists at the graph-declared path, proving
        the test ran during the build phase and the marker landed where the
        rest of compiletools expects it (not buried inside cmake-build/)."""
        (tmp_path / "unit_test.hpp").write_text("#pragma once\n")
        test_src = tmp_path / "test_pass.cpp"
        test_src.write_text('#include "unit_test.hpp"\nint main() { return 0; }\n')

        backend, graph = uth.build_real_backend(CMakeBackend, tmp_path, [], tests=[test_src])
        with open(tmp_path / "CMakeLists.txt", "w") as f:
            backend.generate(graph, output=f)

        backend.execute("build")

        markers = uth.find_result_markers(tmp_path)
        assert markers, "no .result marker after execute('build') — test did not run during the build phase"
        # add_custom_command resolves a relative OUTPUT against the build dir;
        # the marker must be anchored to the source tree, not stranded under
        # cmake-build/.
        assert not any("cmake-build" in m for m in markers), (
            f".result marker landed inside cmake-build/ instead of the graph path: {markers}"
        )
        test_rule = next(r for r in graph.rules if r.rule_type == "test")
        marker = test_rule.success_marker
        assert marker is not None
        assert os.path.exists(os.path.join(tmp_path, marker)), (
            f"marker not at the graph-declared path {marker}; found {markers}"
        )

    @uth.requires_functional_compiler
    def test_cmake_test_failure_fails_build(self, tmp_path):
        """A failing test must make execute("build") raise CalledProcessError,
        and the failing test's ``.result`` marker must NOT be created (the
        touch only runs after the test exits 0)."""
        (tmp_path / "unit_test.hpp").write_text("#pragma once\n")
        test_src = tmp_path / "test_fail.cpp"
        test_src.write_text('#include "unit_test.hpp"\nint main() { return 1; }\n')

        backend, graph = uth.build_real_backend(CMakeBackend, tmp_path, [], tests=[test_src])
        with open(tmp_path / "CMakeLists.txt", "w") as f:
            backend.generate(graph, output=f)

        with pytest.raises(subprocess.CalledProcessError):
            backend.execute("build")

        results = uth.find_result_markers(tmp_path)
        assert not results, f"failing test left a .result marker (touch ran despite rc!=0): {results}"
