"""Unit tests for the CMake build backend (no compiler required)."""

import io
from unittest.mock import MagicMock, patch

import pytest

from compiletools.build_backend import extract_copts, extract_linkopts, get_backend_class
from compiletools.build_graph import BuildGraph, BuildRule
from compiletools.cmake_backend import CMakeBackend, _cmake_quote_copt, _filter_x_lang_copts, _separate_include_dirs


class TestCMakeBackendRegistered:
    def test_registered_as_cmake(self):
        cls = get_backend_class("cmake")
        assert cls is CMakeBackend

    def test_name(self):
        assert CMakeBackend.name() == "cmake"

    def test_build_filename(self):
        assert CMakeBackend.build_filename() == "CMakeLists.txt"


class TestCMakeGenerate:
    def _make_backend(self):
        args = MagicMock()
        hunter = MagicMock()
        return CMakeBackend(args=args, hunter=hunter)

    def test_header_comment(self):
        graph = BuildGraph()
        backend = self._make_backend()
        buf = io.StringIO()
        backend.generate(graph, output=buf)
        content = buf.getvalue()

        assert "CMakeLists.txt generated by compiletools" in content

    def test_cmake_minimum_required(self):
        graph = BuildGraph()
        backend = self._make_backend()
        buf = io.StringIO()
        backend.generate(graph, output=buf)
        content = buf.getvalue()

        assert "cmake_minimum_required(VERSION 3.15)" in content

    def test_project_declaration(self):
        graph = BuildGraph()
        backend = self._make_backend()
        buf = io.StringIO()
        backend.generate(graph, output=buf)
        content = buf.getvalue()

        assert "project(compiletools_build CXX)" in content

    def test_single_source_executable(self):
        graph = BuildGraph()
        graph.add_rule(
            BuildRule(
                output="obj/hello.o",
                inputs=["hello.cpp"],
                command=["g++", "-O2", "-c", "hello.cpp", "-o", "obj/hello.o"],
                rule_type="compile",
            )
        )
        graph.add_rule(
            BuildRule(
                output="bin/hello",
                inputs=["obj/hello.o"],
                command=["g++", "-o", "bin/hello", "obj/hello.o"],
                rule_type="link",
            )
        )

        backend = self._make_backend()
        buf = io.StringIO()
        backend.generate(graph, output=buf)
        content = buf.getvalue()

        assert "add_executable(hello" in content
        assert "hello.cpp" in content

    def test_multiple_sources(self):
        graph = BuildGraph()
        graph.add_rule(
            BuildRule(
                output="obj/main.o",
                inputs=["main.cpp"],
                command=["g++", "-c", "main.cpp", "-o", "obj/main.o"],
                rule_type="compile",
            )
        )
        graph.add_rule(
            BuildRule(
                output="obj/util.o",
                inputs=["util.cpp", "util.h"],
                command=["g++", "-c", "util.cpp", "-o", "obj/util.o"],
                rule_type="compile",
            )
        )
        graph.add_rule(
            BuildRule(
                output="bin/app",
                inputs=["obj/main.o", "obj/util.o"],
                command=["g++", "-o", "bin/app", "obj/main.o", "obj/util.o"],
                rule_type="link",
            )
        )

        backend = self._make_backend()
        buf = io.StringIO()
        backend.generate(graph, output=buf)
        content = buf.getvalue()

        assert "add_executable(app" in content
        assert "main.cpp" in content
        assert "util.cpp" in content
        assert "util.h" in content

    def test_compile_options(self):
        graph = BuildGraph()
        graph.add_rule(
            BuildRule(
                output="obj/foo.o",
                inputs=["foo.cpp"],
                command=["g++", "-O2", "-std=c++17", "-DFOO=1", "-c", "foo.cpp", "-o", "obj/foo.o"],
                rule_type="compile",
            )
        )
        graph.add_rule(
            BuildRule(
                output="bin/foo",
                inputs=["obj/foo.o"],
                command=["g++", "-o", "bin/foo", "obj/foo.o"],
                rule_type="link",
            )
        )

        backend = self._make_backend()
        buf = io.StringIO()
        backend.generate(graph, output=buf)
        content = buf.getvalue()

        assert "target_compile_options(foo PRIVATE" in content
        assert '"-O2"' in content
        assert '"-std=c++17"' in content
        assert '"-DFOO=1"' in content

    def test_link_options(self):
        graph = BuildGraph()
        graph.add_rule(
            BuildRule(
                output="obj/foo.o",
                inputs=["foo.cpp"],
                command=["g++", "-c", "foo.cpp", "-o", "obj/foo.o"],
                rule_type="compile",
            )
        )
        graph.add_rule(
            BuildRule(
                output="bin/foo",
                inputs=["obj/foo.o"],
                command=["g++", "-o", "bin/foo", "obj/foo.o", "-lm", "-lpthread"],
                rule_type="link",
            )
        )

        backend = self._make_backend()
        buf = io.StringIO()
        backend.generate(graph, output=buf)
        content = buf.getvalue()

        assert "target_link_libraries(foo PRIVATE" in content
        assert '"m"' in content
        assert '"pthread"' in content

    def test_include_dirs_separated(self):
        graph = BuildGraph()
        graph.add_rule(
            BuildRule(
                output="obj/foo.o",
                inputs=["foo.cpp"],
                command=["g++", "-I/usr/include", "-I/opt/local/include", "-Wall", "-c", "foo.cpp", "-o", "obj/foo.o"],
                rule_type="compile",
            )
        )
        graph.add_rule(
            BuildRule(
                output="bin/foo",
                inputs=["obj/foo.o"],
                command=["g++", "-o", "bin/foo", "obj/foo.o"],
                rule_type="link",
            )
        )

        backend = self._make_backend()
        buf = io.StringIO()
        backend.generate(graph, output=buf)
        content = buf.getvalue()

        assert "target_include_directories(foo PRIVATE" in content
        assert '"/usr/include"' in content
        assert '"/opt/local/include"' in content
        # -Wall should be in compile_options, not include_directories
        assert "target_compile_options(foo PRIVATE" in content
        assert '"-Wall"' in content

    def test_empty_graph(self):
        graph = BuildGraph()
        backend = self._make_backend()
        buf = io.StringIO()
        backend.generate(graph, output=buf)
        content = buf.getvalue()

        assert "cmake_minimum_required" in content
        assert "add_executable" not in content

    def test_phony_rules_not_emitted(self):
        graph = BuildGraph()
        graph.add_rule(BuildRule(output="build", inputs=["bin/foo"], command=None, rule_type="phony"))
        graph.add_rule(BuildRule(output="all", inputs=["build"], command=None, rule_type="phony"))

        backend = self._make_backend()
        buf = io.StringIO()
        backend.generate(graph, output=buf)
        content = buf.getvalue()

        assert "add_executable" not in content
        assert "phony" not in content

    def test_headers_in_sources(self):
        graph = BuildGraph()
        graph.add_rule(
            BuildRule(
                output="obj/main.o",
                inputs=["main.cpp", "config.h", "types.h"],
                command=["g++", "-c", "main.cpp", "-o", "obj/main.o"],
                rule_type="compile",
            )
        )
        graph.add_rule(
            BuildRule(
                output="bin/main",
                inputs=["obj/main.o"],
                command=["g++", "-o", "bin/main", "obj/main.o"],
                rule_type="link",
            )
        )

        backend = self._make_backend()
        buf = io.StringIO()
        backend.generate(graph, output=buf)
        content = buf.getvalue()

        assert "config.h" in content
        assert "types.h" in content


class TestCmakeQuoteCopt:
    """``_cmake_quote_copt`` must produce well-formed CMake quoted arguments.

    Tokens are wrapped in ``"..."`` with any embedded ``"`` escaped as ``\\"``
    so that cmake's Makefile generator passes them verbatim to the compiler.
    The specific bug: ``f'"{c}"'`` for ``c = '-DFOO="bar"'`` produced the
    malformed cmake syntax ``"-DFOO="bar""``; the helper fixes that.
    """

    def test_plain_flag_unchanged(self):
        assert _cmake_quote_copt("-O2") == '"-O2"'

    def test_define_without_quotes(self):
        assert _cmake_quote_copt("-DFOO=1") == '"-DFOO=1"'

    def test_flag_with_embedded_double_quotes(self):
        # -DCT_PROJECT_VERSION="1.2.3" must survive cmake quoting so the
        # macro expands to a C string literal, not a bare number.
        result = _cmake_quote_copt('-DCT_PROJECT_VERSION="1.2.3"')
        # Outer quotes + inner " escaped as \":
        assert result == '"-DCT_PROJECT_VERSION=\\"1.2.3\\""'
        # The malformed form (pre-fix) must not be produced.
        assert result != '"-DCT_PROJECT_VERSION="1.2.3""'

    def test_flag_with_string_value_name(self):
        assert _cmake_quote_copt('-DCT_PROJECT_NAME="demo_app"') == '"-DCT_PROJECT_NAME=\\"demo_app\\""'

    def test_backslash_escaped(self):
        # A backslash in a token is escaped so cmake does not treat it as
        # the start of an escape sequence inside a quoted arg.
        result = _cmake_quote_copt("-DPATH=a\\b")
        assert result == '"-DPATH=a\\\\b"'


class TestSeparateIncludeDirs:
    def test_separates_i_flags(self):
        copts = ["-I/usr/include", "-O2", "-I/opt/include", "-Wall"]
        dirs, remaining = _separate_include_dirs(copts)
        assert dirs == ["/usr/include", "/opt/include"]
        assert remaining == ["-O2", "-Wall"]

    def test_no_i_flags(self):
        copts = ["-O2", "-Wall"]
        dirs, remaining = _separate_include_dirs(copts)
        assert dirs == []
        assert remaining == ["-O2", "-Wall"]

    def test_empty(self):
        dirs, remaining = _separate_include_dirs([])
        assert dirs == []
        assert remaining == []

    def test_only_i_flags(self):
        copts = ["-I/a", "-I/b"]
        dirs, remaining = _separate_include_dirs(copts)
        assert dirs == ["/a", "/b"]
        assert remaining == []


class TestCoptsExtraction:
    def test_basic_flags(self):
        cmd = ["g++", "-O2", "-std=c++17", "-c", "foo.cpp", "-o", "obj/foo.o"]
        assert extract_copts(cmd) == ["-O2", "-std=c++17"]

    def test_empty_command(self):
        assert extract_copts([]) == []


class TestLinkoptsExtraction:
    def test_library_flags(self):
        cmd = ["g++", "-o", "bin/foo", "obj/foo.o", "-lm", "-lpthread"]
        objs = {"obj/foo.o"}
        assert extract_linkopts(cmd, objs) == ["-lm", "-lpthread"]

    def test_empty_command(self):
        assert extract_linkopts([], set()) == []


class TestCMakeExecute:
    def test_raises_when_cmake_not_found(self):
        args = MagicMock()
        hunter = MagicMock()
        backend = CMakeBackend(args=args, hunter=hunter)

        with patch("shutil.which", return_value=None):
            with pytest.raises(RuntimeError, match=r"cmake.*not found"):
                backend.execute()

    def _capture_configure(self, *, CXX, CC, tmp_path):
        """Run _execute_build('build') with subprocess and FS calls stubbed,
        returning the configure command list."""
        import os

        args = MagicMock()
        args.CXX = CXX
        args.CC = CC
        args.cas_objdir = str(tmp_path / "obj")
        args.parallel = 0
        args.output = str(tmp_path / "out")
        os.makedirs(args.cas_objdir, exist_ok=True)

        hunter = MagicMock()
        backend = CMakeBackend(args=args, hunter=hunter)
        backend._graph = None

        captured = []

        def fake_check_call(cmd, **kwargs):
            captured.append(cmd)

        with (
            patch("shutil.which", return_value="/usr/bin/cmake"),
            patch("subprocess.check_call", side_effect=fake_check_call),
            patch.object(backend, "_copy_built_executables"),
            patch.object(backend, "build_filename", return_value=str(tmp_path / "CMakeLists.txt")),
        ):
            (tmp_path / "CMakeLists.txt").write_text("")
            backend._execute_build("build")

        # First call is configure
        return captured[0]

    def test_configure_with_plain_compiler(self, tmp_path):
        """Without a wrapper, CMAKE_CXX_COMPILER gets the bare compiler and
        no LAUNCHER variable is emitted."""
        cmd = self._capture_configure(CXX="g++", CC="gcc", tmp_path=tmp_path)

        assert "-DCMAKE_CXX_COMPILER=g++" in cmd
        assert "-DCMAKE_C_COMPILER=gcc" in cmd
        assert not any(a.startswith("-DCMAKE_CXX_COMPILER_LAUNCHER=") for a in cmd)
        assert not any(a.startswith("-DCMAKE_C_COMPILER_LAUNCHER=") for a in cmd)

    def test_configure_with_ccache_wrapper(self, tmp_path):
        """``CXX='ccache g++'`` must split into COMPILER + COMPILER_LAUNCHER —
        passing the literal string to -DCMAKE_CXX_COMPILER would fail because
        CMake expects a single executable path."""
        cmd = self._capture_configure(CXX="ccache g++", CC="ccache gcc", tmp_path=tmp_path)

        assert "-DCMAKE_CXX_COMPILER=g++" in cmd, f"Expected bare compiler in CMAKE_CXX_COMPILER; got {cmd}"
        assert "-DCMAKE_C_COMPILER=gcc" in cmd, f"Expected bare compiler in CMAKE_C_COMPILER; got {cmd}"
        assert "-DCMAKE_CXX_COMPILER_LAUNCHER=ccache" in cmd, (
            f"Expected wrapper in CMAKE_CXX_COMPILER_LAUNCHER; got {cmd}"
        )
        assert "-DCMAKE_C_COMPILER_LAUNCHER=ccache" in cmd, f"Expected wrapper in CMAKE_C_COMPILER_LAUNCHER; got {cmd}"
        # The literal "ccache g++" must never appear as an argument value
        assert not any("ccache g++" in a for a in cmd), (
            f"CMake compiler argument still contains the literal wrapped string: {cmd}"
        )


class TestCMakeAllOutputsCurrent:
    """CMake backends place outputs in cmake-build/, not at namer paths,
    so the base-class _all_outputs_current pre-check would mis-fire.
    The override must return False unconditionally so the build (and
    post-build copy) always runs."""

    def test_always_returns_false_even_when_outputs_exist(self, tmp_path):
        args = MagicMock()
        hunter = MagicMock()
        backend = CMakeBackend(args=args, hunter=hunter)

        # Build a graph whose compile/link outputs exist on disk and have
        # matching link signatures — base class would return True.
        from compiletools.build_backend import compute_link_signature

        obj_path = str(tmp_path / "foo.o")
        exe_path = str(tmp_path / "main")
        with open(obj_path, "w") as f:
            f.write("object")
        with open(exe_path, "w") as f:
            f.write("executable")

        graph = BuildGraph()
        graph.add_rule(BuildRule(output=obj_path, inputs=["foo.cpp"], command=["g++"], rule_type="compile"))
        link_rule = BuildRule(
            output=exe_path, inputs=[obj_path], command=["g++", "-o", exe_path, obj_path], rule_type="link"
        )
        graph.add_rule(link_rule)
        with open(exe_path + ".ct-sig", "w") as f:
            f.write(compute_link_signature(link_rule))

        # CMake override must still return False — defer to CMake.
        assert backend._all_outputs_current(graph) is False

    def test_always_returns_false_with_empty_graph(self):
        args = MagicMock()
        hunter = MagicMock()
        backend = CMakeBackend(args=args, hunter=hunter)
        assert backend._all_outputs_current(BuildGraph()) is False


class TestFilterXLangCopts:
    """Unit tests for _filter_x_lang_copts helper."""

    def test_removes_orphan_x_flag(self):
        # extract_copts produces an orphan -x (c++ argument is dropped)
        copts = ["-std=c++20", "-fmodules-ts", "-x"]
        assert _filter_x_lang_copts(copts) == ["-std=c++20", "-fmodules-ts"]

    def test_removes_x_with_paired_lang_arg(self):
        # If somehow -x c++ appears as two elements
        copts = ["-std=c++20", "-x", "c++", "-fmodules-ts"]
        assert _filter_x_lang_copts(copts) == ["-std=c++20", "-fmodules-ts"]

    def test_no_x_flag_unchanged(self):
        copts = ["-std=c++20", "-O2", "-Wall"]
        assert _filter_x_lang_copts(copts) == ["-std=c++20", "-O2", "-Wall"]

    def test_empty(self):
        assert _filter_x_lang_copts([]) == []

    def test_x_flag_at_end_removed(self):
        copts = ["-O2", "-x"]
        assert _filter_x_lang_copts(copts) == ["-O2"]


class TestCppmPerSourceProperties:
    """Test that .cppm sources get per-source set_source_files_properties and
    -x is NOT in global target_compile_options.

    Background: gcc injects ``-x c++`` immediately before the .cppm filename
    so it recognises the extension as C++ source.  build_backend.extract_copts
    keeps the orphan ``-x`` (``c++`` is not flag-shaped) and aggregate_rule_sources
    deduplicates it into all_copts.  cmake's target_compile_options then emits
    that orphan at global scope; gcc interprets the next token (cmake's own
    ``-MD``) as the language argument and raises:
        g++: error: language -MD not recognized
    Fix: filter ``-x`` from global copts, emit per-source
    set_source_files_properties for each .cppm file.
    """

    def _make_backend(self):
        args = MagicMock()
        hunter = MagicMock()
        return CMakeBackend(args=args, hunter=hunter)

    def _build_graph_with_cppm(self, cppm_path: str = "math.cppm") -> BuildGraph:
        """Return a minimal BuildGraph: one .cppm compile + one link rule."""
        graph = BuildGraph()
        # The compile command mirrors what build_backend._create_compile_rule emits
        # for a gcc .cppm file: -x c++ placed immediately before the filename.
        graph.add_rule(
            BuildRule(
                output="obj/math.o",
                inputs=[cppm_path],
                command=[
                    "g++",
                    "-std=c++20",
                    "-fmodules-ts",
                    "-c",
                    "-x",
                    "c++",
                    cppm_path,
                    "-o",
                    "obj/math.o",
                ],
                rule_type="compile",
            )
        )
        graph.add_rule(
            BuildRule(
                output="bin/math",
                inputs=["obj/math.o"],
                command=["g++", "-o", "bin/math", "obj/math.o"],
                rule_type="link",
            )
        )
        return graph

    def test_cppm_has_per_source_compile_options(self):
        """set_source_files_properties must appear for the .cppm source."""
        graph = self._build_graph_with_cppm("math.cppm")
        backend = self._make_backend()
        buf = __import__("io").StringIO()
        backend.generate(graph, output=buf)
        content = buf.getvalue()

        assert "set_source_files_properties" in content
        assert "math.cppm" in content
        # The per-source block must contain COMPILE_OPTIONS and LANGUAGE CXX
        assert "COMPILE_OPTIONS" in content
        assert "LANGUAGE CXX" in content

    def test_cppm_per_source_contains_x_cxx(self):
        """The per-source COMPILE_OPTIONS must encode -x;c++ (cmake list separator)."""
        graph = self._build_graph_with_cppm("math.cppm")
        backend = self._make_backend()
        buf = __import__("io").StringIO()
        backend.generate(graph, output=buf)
        content = buf.getvalue()

        # Check that -x and c++ appear in the set_source_files_properties block
        lines = content.splitlines()
        ssf_lines = [ln for ln in lines if "set_source_files_properties" in ln or "COMPILE_OPTIONS" in ln]
        combined = "\n".join(ssf_lines)
        assert "-x" in combined
        assert "c++" in combined

    def test_global_target_compile_options_no_x_flag(self):
        """The orphan -x must NOT appear in global target_compile_options."""
        graph = self._build_graph_with_cppm("math.cppm")
        backend = self._make_backend()
        buf = __import__("io").StringIO()
        backend.generate(graph, output=buf)
        content = buf.getvalue()

        lines = content.splitlines()
        tco_lines = [ln for ln in lines if "target_compile_options" in ln]
        for ln in tco_lines:
            assert '"-x"' not in ln, f"Orphan -x found in global target_compile_options: {ln!r}"

    def test_regular_cpp_no_per_source_properties(self):
        """Regular .cpp sources must NOT trigger set_source_files_properties."""
        graph = BuildGraph()
        graph.add_rule(
            BuildRule(
                output="obj/main.o",
                inputs=["main.cpp"],
                command=["g++", "-std=c++20", "-c", "main.cpp", "-o", "obj/main.o"],
                rule_type="compile",
            )
        )
        graph.add_rule(
            BuildRule(
                output="bin/main",
                inputs=["obj/main.o"],
                command=["g++", "-o", "bin/main", "obj/main.o"],
                rule_type="link",
            )
        )
        backend = self._make_backend()
        buf = __import__("io").StringIO()
        backend.generate(graph, output=buf)
        content = buf.getvalue()

        assert "set_source_files_properties" not in content
