"""Tests for the Make backend (MakefileBackend) and makefile.py main()."""

import io
import os
import shutil
import subprocess
from types import SimpleNamespace
from unittest.mock import MagicMock, patch

import compiletools.makefile
import compiletools.testhelper as uth
import compiletools.utils
from compiletools.build_graph import BuildGraph, BuildRule
from compiletools.makefile_backend import MakefileBackend


def _make_args(**overrides):
    """Create a minimal args namespace for MakefileBackend unit tests."""
    defaults = dict(
        file_locking=False,
        verbose=0,
        objdir="/tmp/test_obj",
        bindir="/tmp/test_bin",
        filename=[],
        tests=[],
        static=[],
        dynamic=[],
        makefilename="Makefile",
        build_only_changed=None,
        serialisetests=False,
        TESTPREFIX="",
        CC="gcc",
        CXX="g++",
        CFLAGS="-O2",
        CXXFLAGS="-O2",
        LD="g++",
        LDFLAGS="",
        parallel=1,
        shuffle=False,
        backend="make",
        sleep_interval_lockdir=None,
        sleep_interval_cifs=0.01,
        sleep_interval_flock_fallback=0.01,
        lock_warn_interval=30,
        lock_cross_host_timeout=300,
    )
    defaults.update(overrides)
    return SimpleNamespace(**defaults)


def _make_simple_graph(args=None):
    """Create a simple BuildGraph with compile + link + phony rules."""
    if args is None:
        args = _make_args()
    graph = BuildGraph()
    graph.add_rule(
        BuildRule(
            output=args.objdir,
            inputs=[],
            command=["mkdir", "-p", args.objdir],
            rule_type="mkdir",
        )
    )
    graph.add_rule(
        BuildRule(
            output="/tmp/test_obj/foo.o",
            inputs=["/src/foo.cpp", "/src/foo.h"],
            command=["g++", "-O2", "-c", "/src/foo.cpp", "-o", "/tmp/test_obj/foo.o"],
            rule_type="compile",
            order_only_deps=[args.objdir],
        )
    )
    graph.add_rule(
        BuildRule(
            output="/tmp/test_bin/foo",
            inputs=["/tmp/test_obj/foo.o"],
            command=["g++", "-o", "/tmp/test_bin/foo", "/tmp/test_obj/foo.o"],
            rule_type="link",
        )
    )
    graph.add_rule(
        BuildRule(
            output="build",
            inputs=["/tmp/test_bin/foo"],
            command=None,
            rule_type="phony",
        )
    )
    graph.add_rule(
        BuildRule(
            output="all",
            inputs=["build"],
            command=None,
            rule_type="phony",
        )
    )
    return graph


class TestMakefileBackendWriteMakefile:
    """Test _write_makefile() output."""

    def test_basic_makefile_syntax(self):
        args = _make_args()
        backend = MakefileBackend(args=args, hunter=MagicMock())
        graph = _make_simple_graph(args)

        buf = io.StringIO()
        backend._filesystem_type = None
        backend._write_makefile(graph, buf)
        content = buf.getvalue()

        assert ".DELETE_ON_ERROR:" in content
        assert "MAKEFLAGS += -rR" in content
        assert ".PHONY: build" in content
        assert ".PHONY: all" in content
        assert "/tmp/test_obj/foo.o:" in content
        assert "\t" in content  # Tab-indented recipes

    def test_makefile_has_args_signature(self):
        args = _make_args()
        backend = MakefileBackend(args=args, hunter=MagicMock())
        graph = _make_simple_graph(args)

        buf = io.StringIO()
        backend._filesystem_type = None
        backend._write_makefile(graph, buf)
        content = buf.getvalue()

        assert content.startswith(f"# Makefile generated by {args}")

    def test_verbose_echo_in_compile_rules(self):
        args = _make_args(verbose=1)
        backend = MakefileBackend(args=args, hunter=MagicMock())
        graph = _make_simple_graph(args)

        buf = io.StringIO()
        backend._filesystem_type = None
        backend._write_makefile(graph, buf)
        content = buf.getvalue()

        assert "@echo ... /src/foo.cpp" in content

    def test_verbose_echo_in_link_rules(self):
        args = _make_args(verbose=1)
        backend = MakefileBackend(args=args, hunter=MagicMock())
        graph = _make_simple_graph(args)

        buf = io.StringIO()
        backend._filesystem_type = None
        backend._write_makefile(graph, buf)
        content = buf.getvalue()

        assert "+@echo ... /tmp/test_bin/foo" in content

    def test_clean_rules_present(self):
        args = _make_args()
        backend = MakefileBackend(args=args, hunter=MagicMock())
        graph = _make_simple_graph(args)

        buf = io.StringIO()
        backend._filesystem_type = None
        backend._write_makefile(graph, buf)
        content = buf.getvalue()

        assert ".PHONY: clean" in content
        assert ".PHONY: realclean" in content
        assert "rm -rf" in content

    def test_clean_rules_have_error_ignore_prefix(self):
        args = _make_args()
        backend = MakefileBackend(args=args, hunter=MagicMock())
        graph = _make_simple_graph(args)

        buf = io.StringIO()
        backend._filesystem_type = None
        backend._write_makefile(graph, buf)
        content = buf.getvalue()

        # Both clean and realclean should use - prefix
        lines = content.split("\n")
        clean_recipes = [line for line in lines if line.startswith("\t-")]
        assert len(clean_recipes) >= 2

    @patch("os.path.isfile", return_value=False)
    def test_omits_shell_without_bash(self, _mock_isfile):
        args = _make_args()
        backend = MakefileBackend(args=args, hunter=MagicMock())
        graph = _make_simple_graph(args)

        buf = io.StringIO()
        backend._filesystem_type = None
        backend._write_makefile(graph, buf)
        content = buf.getvalue()

        assert "SHELL" not in content

    def test_order_only_deps_rendered(self):
        args = _make_args()
        backend = MakefileBackend(args=args, hunter=MagicMock())
        graph = _make_simple_graph(args)

        buf = io.StringIO()
        backend._filesystem_type = None
        backend._write_makefile(graph, buf)
        content = buf.getvalue()

        assert f"| {args.objdir}" in content


class TestMakefileBackendFileLocking:
    """Test file-locking integration in _write_makefile()."""

    def test_compile_without_file_locking(self):
        args = _make_args(file_locking=False)
        backend = MakefileBackend(args=args, hunter=MagicMock())
        backend._filesystem_type = None
        graph = _make_simple_graph(args)

        buf = io.StringIO()
        backend._write_makefile(graph, buf)
        content = buf.getvalue()

        assert "ct-lock-helper" not in content

    def test_compile_with_lockdir_strategy(self):
        args = _make_args(file_locking=True, sleep_interval_lockdir=0.05)
        backend = MakefileBackend(args=args, hunter=MagicMock())
        backend._filesystem_type = "nfs"
        graph = _make_simple_graph(args)

        buf = io.StringIO()
        backend._write_makefile(graph, buf)
        content = buf.getvalue()

        assert "ct-lock-helper" in content
        assert "--strategy=lockdir" in content
        assert "CT_LOCK_SLEEP_INTERVAL=0.05" in content

    def test_compile_with_cifs_strategy(self):
        args = _make_args(file_locking=True, sleep_interval_cifs=0.02)
        backend = MakefileBackend(args=args, hunter=MagicMock())
        backend._filesystem_type = "cifs"
        graph = _make_simple_graph(args)

        buf = io.StringIO()
        with patch("compiletools.filesystem_utils.get_lock_strategy", return_value="cifs"):
            backend._write_makefile(graph, buf)
        content = buf.getvalue()

        assert "--strategy=cifs" in content
        assert "CT_LOCK_SLEEP_INTERVAL_CIFS=0.02" in content

    def test_compile_with_flock_strategy(self):
        args = _make_args(file_locking=True, sleep_interval_flock_fallback=0.03)
        backend = MakefileBackend(args=args, hunter=MagicMock())
        backend._filesystem_type = "ext4"
        graph = _make_simple_graph(args)

        buf = io.StringIO()
        with patch("compiletools.filesystem_utils.get_lock_strategy", return_value="flock"), \
             patch("compiletools.build_backend._native_flock_available", return_value=True):
            backend._write_makefile(graph, buf)
        content = buf.getvalue()

        # Native flock binary used instead of ct-lock-helper
        assert "flock " in content
        assert "ct-lock-helper" not in content

    def test_compile_with_flock_strategy_fallback(self):
        """Falls back to ct-lock-helper when native flock binary is unavailable."""
        args = _make_args(file_locking=True, sleep_interval_flock_fallback=0.03)
        backend = MakefileBackend(args=args, hunter=MagicMock())
        backend._filesystem_type = "ext4"
        graph = _make_simple_graph(args)

        buf = io.StringIO()
        with patch("compiletools.filesystem_utils.get_lock_strategy", return_value="flock"), \
             patch("compiletools.build_backend._native_flock_available", return_value=False):
            backend._write_makefile(graph, buf)
        content = buf.getvalue()

        assert "--strategy=flock" in content
        assert "CT_LOCK_SLEEP_INTERVAL_FLOCK=0.03" in content

    def test_validate_umask_warning(self, capsys):
        args = _make_args(file_locking=True, verbose=1)
        backend = MakefileBackend(args=args, hunter=MagicMock())
        old_umask = os.umask(0o077)
        try:
            backend._validate_umask_for_file_locking()
        finally:
            os.umask(old_umask)
        captured = capsys.readouterr()
        assert "restrictive umask" in captured.err

    def test_validate_umask_no_warning_permissive(self, capsys):
        args = _make_args(file_locking=True, verbose=1)
        backend = MakefileBackend(args=args, hunter=MagicMock())
        old_umask = os.umask(0o002)
        try:
            backend._validate_umask_for_file_locking()
        finally:
            os.umask(old_umask)
        captured = capsys.readouterr()
        assert "restrictive umask" not in captured.err

    def test_link_rule_wrapped_with_lock_helper(self):
        """Link rules include ct-lock-helper link when file_locking=True."""
        import pytest

        args = _make_args(file_locking=True, sleep_interval_lockdir=0.05)
        backend = MakefileBackend(args=args, hunter=MagicMock())
        backend._filesystem_type = "nfs"
        graph = _make_simple_graph(args)

        buf = io.StringIO()
        backend._write_makefile(graph, buf)
        content = buf.getvalue()

        # Find the link rule line
        for line in content.splitlines():
            if "/tmp/test_bin/foo" in line and "g++" in line and "-o" in line:
                assert "ct-lock-helper link" in line, f"Link rule not wrapped: {line}"
                assert "--strategy=lockdir" in line
                break
        else:
            pytest.fail("link rule command not found in Makefile output")

    def test_static_library_rule_wrapped_with_lock_helper(self):
        """Static library (ar) rules include ct-lock-helper link when file_locking=True."""
        import pytest

        args = _make_args(file_locking=True, sleep_interval_lockdir=0.05)
        backend = MakefileBackend(args=args, hunter=MagicMock())
        backend._filesystem_type = "nfs"

        graph = BuildGraph()
        graph.add_rule(
            BuildRule(
                output="/tmp/test_obj/libfoo.a",
                inputs=["/tmp/test_obj/foo.o"],
                command=["ar", "rcs", "-o", "/tmp/test_obj/libfoo.a", "/tmp/test_obj/foo.o"],
                rule_type="static_library",
            )
        )

        buf = io.StringIO()
        backend._write_makefile(graph, buf)
        content = buf.getvalue()

        for line in content.splitlines():
            if "libfoo.a" in line and "ar" in line:
                assert "ct-lock-helper link" in line, f"ar rule not wrapped: {line}"
                break
        else:
            pytest.fail("static_library rule command not found in Makefile output")

    def test_link_rule_not_wrapped_when_locking_disabled(self):
        """Link rules are NOT wrapped when file_locking=False."""
        args = _make_args(file_locking=False)
        backend = MakefileBackend(args=args, hunter=MagicMock())
        backend._filesystem_type = None
        graph = _make_simple_graph(args)

        buf = io.StringIO()
        backend._write_makefile(graph, buf)
        content = buf.getvalue()

        for line in content.splitlines():
            if "/tmp/test_bin/foo" in line and "g++" in line:
                assert "ct-lock-helper" not in line
                break


class TestWrapLinkWithLock:
    """Test wrap_link_with_lock() function in build_backend."""

    def test_wraps_link_with_lockdir(self):
        from compiletools.build_backend import wrap_link_with_lock

        args = _make_args(
            file_locking=True,
            sleep_interval_lockdir=0.05,
            lock_warn_interval=30,
            lock_cross_host_timeout=600,
        )
        result = wrap_link_with_lock(
            "g++ -o /tmp/test_bin/foo /tmp/test_obj/foo.o",
            "/tmp/test_bin/foo",
            args,
            "nfs",
        )
        assert "ct-lock-helper link" in result
        assert "--strategy=lockdir" in result
        assert "--target=/tmp/test_bin/foo" in result
        assert "CT_LOCK_SLEEP_INTERVAL=0.05" in result
        assert "g++ -o /tmp/test_bin/foo /tmp/test_obj/foo.o" in result

    def test_wraps_link_with_flock(self):
        from compiletools.build_backend import wrap_link_with_lock

        args = _make_args(
            file_locking=True,
            sleep_interval_flock_fallback=0.03,
            lock_warn_interval=30,
            lock_cross_host_timeout=600,
        )
        with patch("compiletools.filesystem_utils.get_lock_strategy", return_value="flock"), \
             patch("compiletools.build_backend._native_flock_available", return_value=True):
            result = wrap_link_with_lock(
                "g++ -o bin/foo obj/foo.o",
                "bin/foo",
                args,
                "ext4",
            )
        # Native flock binary used instead of ct-lock-helper
        assert result == "flock bin/foo g++ -o bin/foo obj/foo.o"
        assert "ct-lock-helper" not in result

    def test_wraps_link_with_flock_fallback(self):
        """Falls back to ct-lock-helper when native flock is unavailable."""
        from compiletools.build_backend import wrap_link_with_lock

        args = _make_args(
            file_locking=True,
            sleep_interval_flock_fallback=0.03,
            lock_warn_interval=30,
            lock_cross_host_timeout=600,
        )
        with patch("compiletools.filesystem_utils.get_lock_strategy", return_value="flock"), \
             patch("compiletools.build_backend._native_flock_available", return_value=False):
            result = wrap_link_with_lock(
                "g++ -o bin/foo obj/foo.o",
                "bin/foo",
                args,
                "ext4",
            )
        assert "ct-lock-helper link" in result
        assert "--strategy=flock" in result
        assert "CT_LOCK_SLEEP_INTERVAL_FLOCK=0.03" in result

    def test_no_wrap_when_locking_disabled(self):
        from compiletools.build_backend import wrap_link_with_lock

        args = _make_args(file_locking=False)
        result = wrap_link_with_lock(
            "g++ -o bin/foo obj/foo.o",
            "bin/foo",
            args,
            "nfs",
        )
        assert "ct-lock-helper" not in result
        assert result == "g++ -o bin/foo obj/foo.o"


class TestMakefileBackendUptodate:
    """Test _build_file_uptodate()."""

    def test_no_makefile(self):
        args = _make_args(makefilename="/tmp/nonexistent_makefile_xyz", verbose=8)
        backend = MakefileBackend(args=args, hunter=MagicMock())
        graph = _make_simple_graph(args)
        assert backend._build_file_uptodate(graph) is False

    def test_changed_args(self, tmp_path):
        makefile_path = str(tmp_path / "Makefile")
        with open(makefile_path, "w") as f:
            f.write("# Makefile generated by old_args\n")

        args = _make_args(makefilename=makefile_path, verbose=8)
        backend = MakefileBackend(args=args, hunter=MagicMock())
        graph = _make_simple_graph(args)
        assert backend._build_file_uptodate(graph) is False

    def test_matching_args_no_deps(self, tmp_path):
        args = _make_args(makefilename=str(tmp_path / "Makefile"), verbose=10)
        makefile_path = str(tmp_path / "Makefile")
        expected_header = f"# Makefile generated by {args}"
        with open(makefile_path, "w") as f:
            f.write(expected_header + "\n")

        backend = MakefileBackend(args=args, hunter=MagicMock())
        # Empty graph has no compile rules to check
        graph = BuildGraph()
        assert backend._build_file_uptodate(graph) is True

    def test_dep_newer_than_makefile(self, tmp_path):
        args = _make_args(makefilename=str(tmp_path / "Makefile"), verbose=8)
        makefile_path = str(tmp_path / "Makefile")
        expected_header = f"# Makefile generated by {args}"
        with open(makefile_path, "w") as f:
            f.write(expected_header + "\n")

        backend = MakefileBackend(args=args, hunter=MagicMock())
        graph = _make_simple_graph(args)

        with patch("compiletools.wrappedos.getmtime") as mock_getmtime:
            mock_getmtime.side_effect = lambda f: 100.0 if f == makefile_path else 200.0
            assert backend._build_file_uptodate(graph) is False

    def test_dep_older_than_makefile(self, tmp_path):
        args = _make_args(makefilename=str(tmp_path / "Makefile"), verbose=10)
        makefile_path = str(tmp_path / "Makefile")
        expected_header = f"# Makefile generated by {args}"
        with open(makefile_path, "w") as f:
            f.write(expected_header + "\n")

        backend = MakefileBackend(args=args, hunter=MagicMock())
        graph = _make_simple_graph(args)

        with patch("compiletools.wrappedos.getmtime") as mock_getmtime:
            mock_getmtime.side_effect = lambda f: 200.0 if f == makefile_path else 100.0
            assert backend._build_file_uptodate(graph) is True


class TestMakefileBackendGenerate:
    """Test generate() with output=None writes to disk."""

    def test_generate_writes_makefile(self, tmp_path):
        makefile_path = str(tmp_path / "Makefile")
        args = _make_args(makefilename=makefile_path)
        backend = MakefileBackend(args=args, hunter=MagicMock())
        graph = _make_simple_graph(args)

        backend.generate(graph)

        assert os.path.exists(makefile_path)
        with open(makefile_path) as f:
            content = f.read()
        assert ".DELETE_ON_ERROR:" in content

    def test_generate_skips_when_uptodate(self, tmp_path):
        makefile_path = str(tmp_path / "Makefile")
        args = _make_args(makefilename=makefile_path, verbose=10)
        backend = MakefileBackend(args=args, hunter=MagicMock())

        # Write a Makefile with matching signature
        graph = BuildGraph()  # No compile rules
        expected_header = f"# Makefile generated by {args}"
        with open(makefile_path, "w") as f:
            f.write(expected_header + "\n")
            f.write("existing content\n")

        backend.generate(graph)

        # Should not have been overwritten
        with open(makefile_path) as f:
            content = f.read()
        assert "existing content" in content

    def test_generate_applies_build_only_changed(self, tmp_path):
        makefile_path = str(tmp_path / "Makefile")
        args = _make_args(makefilename=makefile_path, build_only_changed="/src/foo.cpp")
        backend = MakefileBackend(args=args, hunter=MagicMock())
        graph = _make_simple_graph(args)

        # Add another compile rule that should be filtered out
        graph.add_rule(
            BuildRule(
                output="/tmp/test_obj/bar.o",
                inputs=["/src/bar.cpp", "/src/bar.h"],
                command=["g++", "-O2", "-c", "/src/bar.cpp", "-o", "/tmp/test_obj/bar.o"],
                rule_type="compile",
                order_only_deps=[args.objdir],
            )
        )

        backend.generate(graph)

        with open(makefile_path) as f:
            content = f.read()
        # foo.o should be present (depends on changed file)
        assert "/tmp/test_obj/foo.o" in content
        # bar.o should not be present (doesn't depend on changed file)
        assert "/tmp/test_obj/bar.o" not in content


class TestMakefileBackendExecute:
    """Test execute() method."""

    def test_execute_runtests_delegates_to_run_tests(self):
        args = _make_args()
        backend = MakefileBackend(args=args, hunter=MagicMock())
        with patch.object(backend, "_run_tests") as mock_run_tests:
            backend.execute("runtests")
            mock_run_tests.assert_called_once()


class TestMakefile:
    """Integration tests using makefile.py main() (which now delegates to MakefileBackend)."""

    def setup_method(self):
        uth.reset()

    def _create_makefile_and_make(self, tempdir):
        origdir = uth.ctdir()
        print("origdir=" + origdir)
        print(tempdir)
        samplesdir = uth.samplesdir()
        print("samplesdir=" + samplesdir)

        with uth.DirectoryContext(tempdir), uth.TempConfigContext(tempdir=tempdir) as temp_config_name:
            relativepaths = [
                "numbers/test_direct_include.cpp",
                "factory/test_factory.cpp",
                "simple/helloworld_c.c",
                "simple/helloworld_cpp.cpp",
                "dottypaths/dottypaths.cpp",
            ]
            realpaths = [os.path.join(samplesdir, filename) for filename in relativepaths]
            with uth.ParserContext():
                compiletools.makefile.main(["--config=" + temp_config_name, "--no-file-locking"] + realpaths)

            filelist = os.listdir(".")
            makefilename = [ff for ff in filelist if ff.startswith("Makefile")]
            cmd = ["make", "-f"] + makefilename
            subprocess.check_output(cmd, universal_newlines=True)

            # Check that an executable got built for each cpp
            actual_exes = set()
            for root, _dirs, files in os.walk(tempdir):
                for ff in files:
                    if compiletools.utils.is_executable(os.path.join(root, ff)):
                        actual_exes.add(ff)
                        print(root + " " + ff)

            expected_exes = {os.path.splitext(os.path.split(filename)[1])[0] for filename in relativepaths}
            assert expected_exes == actual_exes

    @uth.requires_functional_compiler
    def test_makefile(self):
        with uth.TempDirContextNoChange() as tempdir1:
            self._create_makefile_and_make(tempdir1)

    @uth.requires_functional_compiler
    def test_static_library(self):
        _test_library("--static")

    @uth.requires_functional_compiler
    def test_dynamic_library(self):
        _test_library("--dynamic")

    @uth.requires_functional_compiler
    def test_file_locking_propagates_compiler_errors(self):
        """Test that compiler errors fail the build when using --file-locking.

        Regression test for bug where set -e was missing from locking recipes,
        causing compiler failures to be silently ignored.
        """
        with uth.TempDirContextWithChange() as tempdir:
            bad_source = os.path.join(tempdir, "test_syntax_error.cpp")
            with open(bad_source, "w") as f:
                f.write("""
// ct-exemarker
int main() {
    this_is_a_syntax_error;  // Intentional error
    return 0;
}
""")

            with uth.TempConfigContext(tempdir=tempdir) as temp_config_name:
                with uth.ParserContext():
                    compiletools.makefile.main(["--config=" + temp_config_name, bad_source, "--file-locking"])

                filelist = os.listdir(".")
                makefilename = [ff for ff in filelist if ff.startswith("Makefile")]
                assert makefilename, "Makefile should have been generated"

                with open(makefilename[0]) as f:
                    makefile_content = f.read()
                    assert "ct-lock-helper" in makefile_content or "flock " in makefile_content, (
                        "Makefile should use ct-lock-helper or native flock for file locking"
                    )

                cmd = ["make", "-f"] + makefilename
                result = subprocess.run(cmd, capture_output=True, text=True)

                assert result.returncode != 0, "Build should fail with non-zero exit code when compiler errors occur"

                combined_output = result.stdout + result.stderr
                assert "error" in combined_output.lower(), "Compiler error message should be visible in output"

    @uth.requires_functional_compiler
    def test_pch_header_builds(self):
        """PCH-HEADER magic flag generates .gch and the executable links correctly."""
        with uth.TempDirContextWithChange() as tempdir:
            # Copy PCH sample to temp dir
            pch_sample = os.path.join(uth.samplesdir(), "pch")
            for f in os.listdir(pch_sample):
                shutil.copy2(os.path.join(pch_sample, f), tempdir)

            source = os.path.join(tempdir, "pch_user.cpp")
            header = os.path.join(tempdir, "stdafx.h")
            assert os.path.isfile(source)
            assert os.path.isfile(header)

            with uth.TempConfigContext(tempdir=tempdir) as temp_config_name:
                with uth.ParserContext():
                    compiletools.makefile.main(
                        ["--config=" + temp_config_name, "--no-file-locking", source]
                    )

                filelist = os.listdir(".")
                makefilename = [ff for ff in filelist if ff.startswith("Makefile")]
                assert makefilename, "Makefile should have been generated"

                with open(makefilename[0]) as f:
                    makefile_content = f.read()
                assert "c++-header" in makefile_content, (
                    "Makefile should contain PCH compile rule with -x c++-header"
                )
                assert ".gch" in makefile_content, (
                    "Makefile should reference .gch output"
                )

                # Build and verify success
                result = subprocess.run(
                    ["make", "-f"] + makefilename,
                    capture_output=True, text=True,
                )
                assert result.returncode == 0, (
                    f"Build should succeed.\nstdout: {result.stdout}\nstderr: {result.stderr}"
                )

                # Verify the .gch was produced
                gch_files = []
                for root, _dirs, files in os.walk(tempdir):
                    for ff in files:
                        if ff.endswith(".gch"):
                            gch_files.append(os.path.join(root, ff))
                assert gch_files, "Build should have produced a .gch file"

                # Verify the executable was produced and runs
                exe_found = False
                for root, _dirs, files in os.walk(tempdir):
                    for ff in files:
                        full = os.path.join(root, ff)
                        if compiletools.utils.is_executable(full) and "pch_user" in ff:
                            exe_found = True
                            run_result = subprocess.run([full], capture_output=True, text=True)
                            assert run_result.returncode == 0
                            assert "pch works" in run_result.stdout
                assert exe_found, "Build should have produced the pch_user executable"

    def teardown_method(self):
        uth.reset()


def _test_library(static_dynamic):
    """Manually specify what files to turn into the static (or dynamic)
    library and test linkage
    """
    samplesdir = uth.samplesdir()

    with uth.TempDirContextWithChange() as tempdir, uth.TempConfigContext(tempdir=tempdir) as temp_config_name:
        exerelativepath = "numbers/test_library.cpp"
        librelativepaths = [
            "numbers/get_numbers.cpp",
            "numbers/get_int.cpp",
            "numbers/get_double.cpp",
        ]
        exerealpath = os.path.join(samplesdir, exerelativepath)
        librealpaths = [os.path.join(samplesdir, filename) for filename in librelativepaths]
        argv = ["--config=" + temp_config_name, "--no-file-locking", exerealpath, static_dynamic] + librealpaths
        compiletools.makefile.main(argv)

        filelist = os.listdir(".")
        makefilename = [ff for ff in filelist if ff.startswith("Makefile")]
        cmd = ["make", "-f"] + makefilename
        subprocess.check_output(cmd, universal_newlines=True)


def test_file_locking_registered_in_apptools():
    """--file-locking is registered centrally in add_locking_arguments(), not per-backend."""
    import configargparse

    from compiletools.apptools import add_locking_arguments

    cap = configargparse.ArgParser()
    add_locking_arguments(cap)

    # Should be able to parse --file-locking and --no-file-locking
    args = cap.parse_args(["--file-locking"])
    assert args.file_locking is True

    args = cap.parse_args(["--no-file-locking"])
    assert args.file_locking is False

    # Default should be True
    args = cap.parse_args([])
    assert args.file_locking is True
