"""Unit tests for the CMake build backend (no compiler required)."""

import io
from unittest.mock import MagicMock, patch

import pytest

from compiletools.build_backend import extract_copts, extract_linkopts, get_backend_class
from compiletools.build_graph import BuildGraph, BuildRule
from compiletools.cmake_backend import CMakeBackend, _separate_include_dirs


class TestCMakeBackendRegistered:
    def test_registered_as_cmake(self):
        cls = get_backend_class("cmake")
        assert cls is CMakeBackend

    def test_name(self):
        assert CMakeBackend.name() == "cmake"

    def test_build_filename(self):
        assert CMakeBackend.build_filename() == "CMakeLists.txt"


class TestCMakeGenerate:
    def _make_backend(self):
        args = MagicMock()
        hunter = MagicMock()
        return CMakeBackend(args=args, hunter=hunter)

    def test_header_comment(self):
        graph = BuildGraph()
        backend = self._make_backend()
        buf = io.StringIO()
        backend.generate(graph, output=buf)
        content = buf.getvalue()

        assert "CMakeLists.txt generated by compiletools" in content

    def test_cmake_minimum_required(self):
        graph = BuildGraph()
        backend = self._make_backend()
        buf = io.StringIO()
        backend.generate(graph, output=buf)
        content = buf.getvalue()

        assert "cmake_minimum_required(VERSION 3.15)" in content

    def test_project_declaration(self):
        graph = BuildGraph()
        backend = self._make_backend()
        buf = io.StringIO()
        backend.generate(graph, output=buf)
        content = buf.getvalue()

        assert "project(compiletools_build CXX)" in content

    def test_single_source_executable(self):
        graph = BuildGraph()
        graph.add_rule(
            BuildRule(
                output="obj/hello.o",
                inputs=["hello.cpp"],
                command=["g++", "-O2", "-c", "hello.cpp", "-o", "obj/hello.o"],
                rule_type="compile",
            )
        )
        graph.add_rule(
            BuildRule(
                output="bin/hello",
                inputs=["obj/hello.o"],
                command=["g++", "-o", "bin/hello", "obj/hello.o"],
                rule_type="link",
            )
        )

        backend = self._make_backend()
        buf = io.StringIO()
        backend.generate(graph, output=buf)
        content = buf.getvalue()

        assert "add_executable(hello" in content
        assert "hello.cpp" in content

    def test_multiple_sources(self):
        graph = BuildGraph()
        graph.add_rule(
            BuildRule(
                output="obj/main.o",
                inputs=["main.cpp"],
                command=["g++", "-c", "main.cpp", "-o", "obj/main.o"],
                rule_type="compile",
            )
        )
        graph.add_rule(
            BuildRule(
                output="obj/util.o",
                inputs=["util.cpp", "util.h"],
                command=["g++", "-c", "util.cpp", "-o", "obj/util.o"],
                rule_type="compile",
            )
        )
        graph.add_rule(
            BuildRule(
                output="bin/app",
                inputs=["obj/main.o", "obj/util.o"],
                command=["g++", "-o", "bin/app", "obj/main.o", "obj/util.o"],
                rule_type="link",
            )
        )

        backend = self._make_backend()
        buf = io.StringIO()
        backend.generate(graph, output=buf)
        content = buf.getvalue()

        assert "add_executable(app" in content
        assert "main.cpp" in content
        assert "util.cpp" in content
        assert "util.h" in content

    def test_compile_options(self):
        graph = BuildGraph()
        graph.add_rule(
            BuildRule(
                output="obj/foo.o",
                inputs=["foo.cpp"],
                command=["g++", "-O2", "-std=c++17", "-DFOO=1", "-c", "foo.cpp", "-o", "obj/foo.o"],
                rule_type="compile",
            )
        )
        graph.add_rule(
            BuildRule(
                output="bin/foo",
                inputs=["obj/foo.o"],
                command=["g++", "-o", "bin/foo", "obj/foo.o"],
                rule_type="link",
            )
        )

        backend = self._make_backend()
        buf = io.StringIO()
        backend.generate(graph, output=buf)
        content = buf.getvalue()

        assert "target_compile_options(foo PRIVATE" in content
        assert '"-O2"' in content
        assert '"-std=c++17"' in content
        assert '"-DFOO=1"' in content

    def test_link_options(self):
        graph = BuildGraph()
        graph.add_rule(
            BuildRule(
                output="obj/foo.o",
                inputs=["foo.cpp"],
                command=["g++", "-c", "foo.cpp", "-o", "obj/foo.o"],
                rule_type="compile",
            )
        )
        graph.add_rule(
            BuildRule(
                output="bin/foo",
                inputs=["obj/foo.o"],
                command=["g++", "-o", "bin/foo", "obj/foo.o", "-lm", "-lpthread"],
                rule_type="link",
            )
        )

        backend = self._make_backend()
        buf = io.StringIO()
        backend.generate(graph, output=buf)
        content = buf.getvalue()

        assert "target_link_libraries(foo PRIVATE" in content
        assert '"m"' in content
        assert '"pthread"' in content

    def test_include_dirs_separated(self):
        graph = BuildGraph()
        graph.add_rule(
            BuildRule(
                output="obj/foo.o",
                inputs=["foo.cpp"],
                command=["g++", "-I/usr/include", "-I/opt/local/include", "-Wall", "-c", "foo.cpp", "-o", "obj/foo.o"],
                rule_type="compile",
            )
        )
        graph.add_rule(
            BuildRule(
                output="bin/foo",
                inputs=["obj/foo.o"],
                command=["g++", "-o", "bin/foo", "obj/foo.o"],
                rule_type="link",
            )
        )

        backend = self._make_backend()
        buf = io.StringIO()
        backend.generate(graph, output=buf)
        content = buf.getvalue()

        assert "target_include_directories(foo PRIVATE" in content
        assert '"/usr/include"' in content
        assert '"/opt/local/include"' in content
        # -Wall should be in compile_options, not include_directories
        assert "target_compile_options(foo PRIVATE" in content
        assert '"-Wall"' in content

    def test_empty_graph(self):
        graph = BuildGraph()
        backend = self._make_backend()
        buf = io.StringIO()
        backend.generate(graph, output=buf)
        content = buf.getvalue()

        assert "cmake_minimum_required" in content
        assert "add_executable" not in content

    def test_phony_rules_not_emitted(self):
        graph = BuildGraph()
        graph.add_rule(BuildRule(output="build", inputs=["bin/foo"], command=None, rule_type="phony"))
        graph.add_rule(BuildRule(output="all", inputs=["build"], command=None, rule_type="phony"))

        backend = self._make_backend()
        buf = io.StringIO()
        backend.generate(graph, output=buf)
        content = buf.getvalue()

        assert "add_executable" not in content
        assert "phony" not in content

    def test_headers_in_sources(self):
        graph = BuildGraph()
        graph.add_rule(
            BuildRule(
                output="obj/main.o",
                inputs=["main.cpp", "config.h", "types.h"],
                command=["g++", "-c", "main.cpp", "-o", "obj/main.o"],
                rule_type="compile",
            )
        )
        graph.add_rule(
            BuildRule(
                output="bin/main",
                inputs=["obj/main.o"],
                command=["g++", "-o", "bin/main", "obj/main.o"],
                rule_type="link",
            )
        )

        backend = self._make_backend()
        buf = io.StringIO()
        backend.generate(graph, output=buf)
        content = buf.getvalue()

        assert "config.h" in content
        assert "types.h" in content


class TestSeparateIncludeDirs:
    def test_separates_i_flags(self):
        copts = ["-I/usr/include", "-O2", "-I/opt/include", "-Wall"]
        dirs, remaining = _separate_include_dirs(copts)
        assert dirs == ["/usr/include", "/opt/include"]
        assert remaining == ["-O2", "-Wall"]

    def test_no_i_flags(self):
        copts = ["-O2", "-Wall"]
        dirs, remaining = _separate_include_dirs(copts)
        assert dirs == []
        assert remaining == ["-O2", "-Wall"]

    def test_empty(self):
        dirs, remaining = _separate_include_dirs([])
        assert dirs == []
        assert remaining == []

    def test_only_i_flags(self):
        copts = ["-I/a", "-I/b"]
        dirs, remaining = _separate_include_dirs(copts)
        assert dirs == ["/a", "/b"]
        assert remaining == []


class TestCoptsExtraction:
    def test_basic_flags(self):
        cmd = ["g++", "-O2", "-std=c++17", "-c", "foo.cpp", "-o", "obj/foo.o"]
        assert extract_copts(cmd) == ["-O2", "-std=c++17"]

    def test_empty_command(self):
        assert extract_copts([]) == []


class TestLinkoptsExtraction:
    def test_library_flags(self):
        cmd = ["g++", "-o", "bin/foo", "obj/foo.o", "-lm", "-lpthread"]
        objs = {"obj/foo.o"}
        assert extract_linkopts(cmd, objs) == ["-lm", "-lpthread"]

    def test_empty_command(self):
        assert extract_linkopts([], set()) == []


class TestCMakeExecute:
    def test_raises_when_cmake_not_found(self):
        args = MagicMock()
        hunter = MagicMock()
        backend = CMakeBackend(args=args, hunter=hunter)

        with patch("shutil.which", return_value=None):
            with pytest.raises(RuntimeError, match=r"cmake.*not found"):
                backend.execute()
