import io
from types import SimpleNamespace
from unittest.mock import MagicMock

from compiletools.build_backend import get_backend_class
from compiletools.build_graph import BuildGraph, BuildRule
from compiletools.tup_backend import TupBackend


class TestTupBackendRegistered:
    def test_registered_as_tup(self):
        cls = get_backend_class("tup")
        assert cls is TupBackend

    def test_name(self):
        assert TupBackend.name() == "tup"

    def test_build_filename(self):
        assert TupBackend.build_filename() == "Tupfile"


class TestTupGenerate:
    def _make_args(self, **overrides):
        defaults = dict(
            verbose=0,
            objdir="/tmp/obj",
            bindir="/tmp/bin",
            git_root="",
            shared_objects=False,
            filename=[],
            tests=[],
            static=[],
            dynamic=[],
            CC="gcc",
            CXX="g++",
            CFLAGS="-O2",
            CXXFLAGS="-O2",
            LD="g++",
            LDFLAGS="",
            serialisetests=False,
            build_only_changed=None,
        )
        defaults.update(overrides)
        return SimpleNamespace(**defaults)

    def test_generate_writes_tup_syntax(self):
        graph = BuildGraph()
        graph.add_rule(
            BuildRule(
                output="obj/foo.o",
                inputs=["foo.cpp", "foo.h"],
                command=["g++", "-O2", "-c", "foo.cpp", "-o", "obj/foo.o"],
                rule_type="compile",
            )
        )
        graph.add_rule(
            BuildRule(
                output="bin/foo",
                inputs=["obj/foo.o"],
                command=["g++", "-o", "bin/foo", "obj/foo.o"],
                rule_type="link",
            )
        )

        args = self._make_args()
        hunter = MagicMock()
        backend = TupBackend(args=args, hunter=hunter)

        buf = io.StringIO()
        backend.generate(graph, output=buf)
        content = buf.getvalue()

        # Tup uses ": inputs |> command |> output" syntax
        assert ": foo.cpp foo.h |> g++ -O2 -c foo.cpp -o obj/foo.o |> obj/foo.o" in content
        assert ": obj/foo.o |> g++ -o bin/foo obj/foo.o |> bin/foo" in content

    def test_order_only_deps(self):
        graph = BuildGraph()
        graph.add_rule(
            BuildRule(
                output="obj/foo.o",
                inputs=["foo.cpp"],
                command=["g++", "-c", "foo.cpp", "-o", "obj/foo.o"],
                rule_type="compile",
                order_only_deps=["/tmp/obj"],
            )
        )

        args = self._make_args()
        hunter = MagicMock()
        backend = TupBackend(args=args, hunter=hunter)

        buf = io.StringIO()
        backend.generate(graph, output=buf)
        content = buf.getvalue()

        assert ": foo.cpp | /tmp/obj |> g++ -c foo.cpp -o obj/foo.o |> obj/foo.o" in content

    def test_phony_rules_skipped(self):
        graph = BuildGraph()
        graph.add_rule(
            BuildRule(
                output="build",
                inputs=["bin/foo"],
                command=None,
                rule_type="phony",
            )
        )

        args = self._make_args()
        hunter = MagicMock()
        backend = TupBackend(args=args, hunter=hunter)

        buf = io.StringIO()
        backend.generate(graph, output=buf)
        content = buf.getvalue()

        # Only the header comment should be present
        assert "Tupfile generated by compiletools" in content
        assert "build" not in content.split("\n", 1)[1]  # No "build" after header

    def test_empty_graph(self):
        graph = BuildGraph()

        args = self._make_args()
        hunter = MagicMock()
        backend = TupBackend(args=args, hunter=hunter)

        buf = io.StringIO()
        backend.generate(graph, output=buf)
        content = buf.getvalue()

        assert "Tupfile generated by compiletools" in content
        # Only the header comment and trailing newline
        lines = [line for line in content.strip().split("\n") if line.strip()]
        assert len(lines) == 1

    def test_command_flags_preserved(self):
        graph = BuildGraph()
        graph.add_rule(
            BuildRule(
                output="obj/bar.o",
                inputs=["bar.cpp"],
                command=["g++", "-Wall", "-Wextra", "-std=c++17", "-c", "bar.cpp", "-o", "obj/bar.o"],
                rule_type="compile",
            )
        )

        args = self._make_args()
        hunter = MagicMock()
        backend = TupBackend(args=args, hunter=hunter)

        buf = io.StringIO()
        backend.generate(graph, output=buf)
        content = buf.getvalue()

        assert "-Wall" in content
        assert "-Wextra" in content
        assert "-std=c++17" in content
