"""Unit tests for the Bazel build backend (no compiler required)."""

import io
from unittest.mock import MagicMock, patch

from compiletools.bazel_backend import BazelBackend
from compiletools.build_backend import extract_copts, extract_linkopts, get_backend_class
from compiletools.build_graph import BuildGraph, BuildRule


class TestBazelBackendRegistered:
    def test_registered_as_bazel(self):
        cls = get_backend_class("bazel")
        assert cls is BazelBackend

    def test_name(self):
        assert BazelBackend.name() == "bazel"

    def test_build_filename(self):
        assert BazelBackend.build_filename() == "BUILD.bazel"


class TestBazelGenerate:
    def _make_backend(self):
        args = MagicMock()
        hunter = MagicMock()
        return BazelBackend(args=args, hunter=hunter)

    def test_single_source_cc_binary(self):
        graph = BuildGraph()
        graph.add_rule(
            BuildRule(
                output="obj/hello.o",
                inputs=["hello.cpp"],
                command=["g++", "-O2", "-c", "hello.cpp", "-o", "obj/hello.o"],
                rule_type="compile",
            )
        )
        graph.add_rule(
            BuildRule(
                output="bin/hello",
                inputs=["obj/hello.o"],
                command=["g++", "-o", "bin/hello", "obj/hello.o"],
                rule_type="link",
            )
        )

        backend = self._make_backend()
        buf = io.StringIO()
        backend.generate(graph, output=buf)
        content = buf.getvalue()

        assert "cc_binary(" in content
        assert 'name = "hello"' in content
        assert '"hello.cpp"' in content

    def test_multiple_sources(self):
        graph = BuildGraph()
        graph.add_rule(
            BuildRule(
                output="obj/main.o",
                inputs=["main.cpp"],
                command=["g++", "-c", "main.cpp", "-o", "obj/main.o"],
                rule_type="compile",
            )
        )
        graph.add_rule(
            BuildRule(
                output="obj/util.o",
                inputs=["util.cpp", "util.h"],
                command=["g++", "-c", "util.cpp", "-o", "obj/util.o"],
                rule_type="compile",
            )
        )
        graph.add_rule(
            BuildRule(
                output="bin/app",
                inputs=["obj/main.o", "obj/util.o"],
                command=["g++", "-o", "bin/app", "obj/main.o", "obj/util.o"],
                rule_type="link",
            )
        )

        backend = self._make_backend()
        buf = io.StringIO()
        backend.generate(graph, output=buf)
        content = buf.getvalue()

        assert 'name = "app"' in content
        assert '"main.cpp"' in content
        assert '"util.cpp"' in content
        assert '"util.h"' in content

    def test_magic_flags_in_copts(self):
        graph = BuildGraph()
        graph.add_rule(
            BuildRule(
                output="obj/foo.o",
                inputs=["foo.cpp"],
                command=["g++", "-O2", "-std=c++17", "-DFOO=1", "-c", "foo.cpp", "-o", "obj/foo.o"],
                rule_type="compile",
            )
        )
        graph.add_rule(
            BuildRule(
                output="bin/foo",
                inputs=["obj/foo.o"],
                command=["g++", "-o", "bin/foo", "obj/foo.o", "-lm"],
                rule_type="link",
            )
        )

        backend = self._make_backend()
        buf = io.StringIO()
        backend.generate(graph, output=buf)
        content = buf.getvalue()

        assert '"-O2"' in content
        assert '"-std=c++17"' in content
        assert '"-DFOO=1"' in content
        assert '"-lm"' in content

    def test_phony_rules_not_emitted(self):
        graph = BuildGraph()
        graph.add_rule(BuildRule(output="build", inputs=["bin/foo"], command=None, rule_type="phony"))
        graph.add_rule(BuildRule(output="all", inputs=["build"], command=None, rule_type="phony"))

        backend = self._make_backend()
        buf = io.StringIO()
        backend.generate(graph, output=buf)
        content = buf.getvalue()

        assert "cc_binary" not in content
        assert "phony" not in content

    def test_empty_graph(self):
        graph = BuildGraph()

        backend = self._make_backend()
        buf = io.StringIO()
        backend.generate(graph, output=buf)
        content = buf.getvalue()

        assert "BUILD.bazel generated by compiletools" in content
        assert "cc_binary" not in content

    def test_headers_in_srcs(self):
        graph = BuildGraph()
        graph.add_rule(
            BuildRule(
                output="obj/main.o",
                inputs=["main.cpp", "config.h", "types.h"],
                command=["g++", "-c", "main.cpp", "-o", "obj/main.o"],
                rule_type="compile",
            )
        )
        graph.add_rule(
            BuildRule(
                output="bin/main",
                inputs=["obj/main.o"],
                command=["g++", "-o", "bin/main", "obj/main.o"],
                rule_type="link",
            )
        )

        backend = self._make_backend()
        buf = io.StringIO()
        backend.generate(graph, output=buf)
        content = buf.getvalue()

        assert '"config.h"' in content
        assert '"types.h"' in content


class TestCoptsExtraction:
    def test_basic_flags(self):
        cmd = ["g++", "-O2", "-std=c++17", "-c", "foo.cpp", "-o", "obj/foo.o"]
        assert extract_copts(cmd, strip_includes=True) == ["-O2", "-std=c++17"]

    def test_define_flags(self):
        cmd = ["g++", "-DFOO=1", "-DBAR", "-c", "foo.cpp", "-o", "obj/foo.o"]
        assert extract_copts(cmd, strip_includes=True) == ["-DFOO=1", "-DBAR"]

    def test_empty_command(self):
        assert extract_copts([]) == []

    def test_complex_flags(self):
        # -I flags are filtered out since Bazel manages includes itself
        cmd = ["g++", "-Wall", "-Wextra", "-I/usr/include", "-c", "x.cpp", "-o", "x.o"]
        assert extract_copts(cmd, strip_includes=True) == ["-Wall", "-Wextra"]


class TestLinkoptsExtraction:
    def test_library_flags(self):
        cmd = ["g++", "-o", "bin/foo", "obj/foo.o", "-lm", "-lpthread"]
        objs = {"obj/foo.o"}
        assert extract_linkopts(cmd, objs) == ["-lm", "-lpthread"]

    def test_no_extra_flags(self):
        cmd = ["g++", "-o", "bin/foo", "obj/foo.o"]
        objs = {"obj/foo.o"}
        assert extract_linkopts(cmd, objs) == []

    def test_empty_command(self):
        assert extract_linkopts([], set()) == []

    def test_multiple_objects_stripped(self):
        cmd = ["g++", "-o", "bin/app", "obj/a.o", "obj/b.o", "-lz"]
        objs = {"obj/a.o", "obj/b.o"}
        assert extract_linkopts(cmd, objs) == ["-lz"]


class TestBazelExecuteRuntests:
    def test_execute_runtests_calls_run_tests(self):
        args = MagicMock()
        args.tests = ["/src/test_foo.cpp"]
        args.verbose = 0
        hunter = MagicMock()
        backend = BazelBackend(args=args, hunter=hunter)

        with patch.object(backend, "_run_tests") as mock_run_tests:
            backend.execute("runtests")
            mock_run_tests.assert_called_once()

    def test_execute_build_does_not_call_run_tests(self):
        args = MagicMock()
        hunter = MagicMock()
        backend = BazelBackend(args=args, hunter=hunter)

        with (
            patch.object(backend, "_run_tests") as mock_run_tests,
            patch("subprocess.check_call"),
            patch("shutil.which", return_value="/usr/bin/bazel"),
            patch("os.path.exists", return_value=False),
            patch("os.path.isdir", return_value=False),
        ):
            backend.execute("build")
            mock_run_tests.assert_not_called()


class TestBazelCopyExecutables:
    def test_copy_built_executables_to_namer_paths(self, tmp_path):
        """After bazel build, executables should be copied to namer paths."""
        # Set up a fake bazel-bin directory
        bazel_bin = tmp_path / "bazel-bin"
        bazel_bin.mkdir()
        exe = bazel_bin / "helloworld_cpp"
        exe.write_text("#!/bin/sh\necho hello")
        exe.chmod(0o755)

        args = MagicMock()
        args.filename = ["/src/helloworld_cpp.cpp"]
        args.tests = []
        hunter = MagicMock()
        backend = BazelBackend(args=args, hunter=hunter)

        dest_path = str(tmp_path / "obj" / "helloworld_cpp")
        backend.namer = MagicMock()
        backend.namer.executable_pathname = MagicMock(return_value=dest_path)

        with patch("compiletools.wrappedos.realpath", side_effect=lambda x: x):
            backend._copy_built_executables(str(bazel_bin))

        import os

        assert os.path.exists(dest_path)

    def test_copy_built_executables_from_subdirectory(self, tmp_path):
        """Executables in subdirectories of bazel-bin should be found."""
        bazel_bin = tmp_path / "bazel-bin"
        (bazel_bin / "subdir" / "pkg").mkdir(parents=True)
        exe = bazel_bin / "subdir" / "pkg" / "myapp"
        exe.write_text("#!/bin/sh\necho hello")
        exe.chmod(0o755)

        args = MagicMock()
        args.filename = ["/src/subdir/myapp.cpp"]
        args.tests = []
        hunter = MagicMock()
        backend = BazelBackend(args=args, hunter=hunter)

        dest_path = str(tmp_path / "obj" / "myapp")
        backend.namer = MagicMock()
        backend.namer.executable_pathname = MagicMock(return_value=dest_path)

        with patch("compiletools.wrappedos.realpath", side_effect=lambda x: x):
            backend._copy_built_executables(str(bazel_bin))

        import os

        assert os.path.exists(dest_path)

    def test_copy_built_executables_mangled_name_in_subdirectory(self, tmp_path):
        """Mangled names in subdirectories should be found and copied."""
        bazel_bin = tmp_path / "bazel-bin"
        (bazel_bin / "src" / "tests").mkdir(parents=True)
        exe = bazel_bin / "src" / "tests" / "my_test_app"
        exe.write_text("#!/bin/sh\necho test")
        exe.chmod(0o755)

        args = MagicMock()
        args.filename = ["/src/my-test-app.cpp"]
        args.tests = []
        hunter = MagicMock()
        backend = BazelBackend(args=args, hunter=hunter)

        dest_path = str(tmp_path / "obj" / "my-test-app")
        backend.namer = MagicMock()
        backend.namer.executable_pathname = MagicMock(return_value=dest_path)

        with patch("compiletools.wrappedos.realpath", side_effect=lambda x: x):
            backend._copy_built_executables(str(bazel_bin))

        import os

        assert os.path.exists(dest_path)


class TestBazelClean:
    def test_clean_runs_bazel_clean_command(self, tmp_path):
        """clean() should invoke 'bazel clean' then call super().clean()."""
        args = MagicMock()
        hunter = MagicMock()
        backend = BazelBackend(args=args, hunter=hunter)
        backend.namer = MagicMock()
        backend.namer.executable_dir.return_value = str(tmp_path / "exe")
        backend.namer.object_dir.return_value = str(tmp_path / "obj")

        with (
            patch("subprocess.check_call") as mock_check_call,
            patch("shutil.which", side_effect=lambda name: "/usr/bin/bazel" if name == "bazel" else None),
        ):
            backend.clean()
            mock_check_call.assert_called_once_with(["/usr/bin/bazel", "clean"], text=True)


class TestBazelExecute:
    def _make_backend(self):
        args = MagicMock()
        hunter = MagicMock()
        return BazelBackend(args=args, hunter=hunter)

    @patch("subprocess.check_call")
    @patch("shutil.which", side_effect=lambda name: "/usr/bin/bazel" if name == "bazel" else None)
    @patch("os.path.exists", return_value=True)
    def test_execute_includes_tls_workaround_when_cacerts_exist(self, mock_exists, mock_which, mock_check_call):
        backend = self._make_backend()
        backend.execute("build")

        cmd = mock_check_call.call_args[0][0]
        assert any("trustStore=" in arg for arg in cmd), f"Expected trustStore in {cmd}"
        assert any("trustStorePassword=" in arg for arg in cmd), f"Expected trustStorePassword in {cmd}"

    @patch("subprocess.check_call")
    @patch("shutil.which", side_effect=lambda name: "/usr/bin/bazel" if name == "bazel" else None)
    @patch("os.path.exists", return_value=False)
    def test_execute_omits_tls_workaround_when_no_cacerts(self, mock_exists, mock_which, mock_check_call):
        backend = self._make_backend()
        backend.execute("build")

        cmd = mock_check_call.call_args[0][0]
        assert not any("trustStore" in arg for arg in cmd), f"Unexpected trustStore in {cmd}"

    @patch("subprocess.check_call")
    @patch("shutil.which", side_effect=lambda name: "/usr/bin/bazel" if name == "bazel" else None)
    @patch("os.path.exists", return_value=False)
    def test_execute_includes_spawn_strategy_and_action_env(self, mock_exists, mock_which, mock_check_call):
        backend = self._make_backend()
        backend.execute("build")

        cmd = mock_check_call.call_args[0][0]
        assert "--spawn_strategy=local" in cmd
        assert "--action_env=PATH" in cmd


class TestBazelGenerateNoFilesystemMutation:
    """generate() to a StringIO must NOT create files in ext/.

    Filesystem mutation (copying out-of-workspace sources into ext/)
    happens in _execute_build → _prepare_external_sources, not in
    generate(). Tests writing to a buffer should leave the cwd clean.
    """

    def test_generate_to_stringio_does_not_create_ext(self, tmp_path, monkeypatch):
        monkeypatch.chdir(tmp_path)
        # Source lives outside the (cwd) workspace, simulating an
        # out-of-tree dependency that would normally trigger the ext/
        # copy code path.
        outside = tmp_path.parent / "outside_src"
        outside.mkdir(exist_ok=True)
        src = outside / "external.cpp"
        src.write_text("int main() { return 0; }\n")

        graph = BuildGraph()
        graph.add_rule(
            BuildRule(
                output="obj/external.o",
                inputs=[str(src)],
                command=["g++", "-c", str(src), "-o", "obj/external.o"],
                rule_type="compile",
            )
        )
        graph.add_rule(
            BuildRule(
                output="bin/external",
                inputs=["obj/external.o"],
                command=["g++", "-o", "bin/external", "obj/external.o"],
                rule_type="link",
            )
        )

        args = MagicMock()
        hunter = MagicMock()
        backend = BazelBackend(args=args, hunter=hunter)

        buf = io.StringIO()
        backend.generate(graph, output=buf)

        # No ext/ directory must have been created in cwd.
        assert not (tmp_path / "ext").exists(), "generate() to StringIO must not create ext/ on disk"
        # And the buffer should contain the bazel rules.
        assert "cc_binary" in buf.getvalue()


class TestBazelPrepareExternalSources:
    """_prepare_external_sources copies out-of-workspace sources into ext/."""

    def test_copies_external_sources(self, tmp_path):
        outside = tmp_path.parent / "external_dir_for_bazel_test"
        outside.mkdir(exist_ok=True)
        src = outside / "ext_source.cpp"
        src.write_text("int main() { return 0; }\n")

        try:
            base_dir = tmp_path / "workspace"
            base_dir.mkdir()

            graph = BuildGraph()
            graph.add_rule(
                BuildRule(
                    output="obj/ext_source.o",
                    inputs=[str(src)],
                    command=["g++", "-c", str(src), "-o", "obj/ext_source.o"],
                    rule_type="compile",
                )
            )
            graph.add_rule(
                BuildRule(
                    output="bin/ext_source",
                    inputs=["obj/ext_source.o"],
                    command=["g++", "-o", "bin/ext_source", "obj/ext_source.o"],
                    rule_type="link",
                )
            )

            args = MagicMock()
            hunter = MagicMock()
            backend = BazelBackend(args=args, hunter=hunter)
            backend._prepare_external_sources(graph, str(base_dir))

            assert (base_dir / "ext" / "ext_source.cpp").exists()
        finally:
            import shutil as _sh

            if outside.exists():
                _sh.rmtree(outside)


class TestBazelAllOutputsCurrent:
    """Bazel backends place outputs in bazel-bin/, not at namer paths,
    so the base-class _all_outputs_current pre-check would mis-fire.
    The override must return False unconditionally so the build (and
    post-build copy from bazel-bin/) always runs."""

    def test_always_returns_false_even_when_outputs_exist(self, tmp_path):
        from compiletools.build_backend import compute_link_signature

        args = MagicMock()
        hunter = MagicMock()
        backend = BazelBackend(args=args, hunter=hunter)

        obj_path = str(tmp_path / "foo.o")
        exe_path = str(tmp_path / "main")
        with open(obj_path, "w") as f:
            f.write("object")
        with open(exe_path, "w") as f:
            f.write("executable")

        graph = BuildGraph()
        graph.add_rule(BuildRule(output=obj_path, inputs=["foo.cpp"], command=["g++"], rule_type="compile"))
        link_rule = BuildRule(
            output=exe_path, inputs=[obj_path], command=["g++", "-o", exe_path, obj_path], rule_type="link"
        )
        graph.add_rule(link_rule)
        with open(exe_path + ".ct-sig", "w") as f:
            f.write(compute_link_signature(link_rule))

        assert backend._all_outputs_current(graph) is False

    def test_always_returns_false_with_empty_graph(self):
        args = MagicMock()
        hunter = MagicMock()
        backend = BazelBackend(args=args, hunter=hunter)
        assert backend._all_outputs_current(BuildGraph()) is False
