"""Tup backend — generates Tupfile build files from a BuildGraph."""

from __future__ import annotations

import compiletools.filesystem_utils
from compiletools.build_backend import BuildBackend, register_backend
from compiletools.build_graph import BuildGraph


@register_backend
class TupBackend(BuildBackend):
    """Generate and execute Tup build files."""

    @staticmethod
    def name() -> str:
        return "tup"

    @staticmethod
    def build_filename() -> str:
        return "Tupfile"

    def generate(self, graph: BuildGraph, output=None) -> None:
        if output is not None:
            self._write_tupfile(graph, output)
        else:
            filename = "Tupfile"
            with compiletools.filesystem_utils.atomic_output_file(filename, mode="w", encoding="utf-8") as f:
                self._write_tupfile(graph, f)

    def _write_tupfile(self, graph: BuildGraph, f) -> None:
        f.write("# Tupfile generated by compiletools\n\n")

        for rule in graph.rules:
            if rule.rule_type == "phony":
                continue  # Tup has no phony rule equivalent
            if not rule.command:
                continue

            cmd = " ".join(rule.command)
            inputs = " ".join(rule.inputs)

            if rule.order_only_deps:
                order_only = " ".join(rule.order_only_deps)
                f.write(f": {inputs} | {order_only} |> {cmd} |> {rule.output}\n")
            else:
                f.write(f": {inputs} |> {cmd} |> {rule.output}\n")

    def execute(self, target: str = "build") -> None:
        if target == "runtests":
            self._run_tests()
            return

        import os
        import shutil
        import subprocess

        if shutil.which("tup") is None:
            raise RuntimeError("tup not found on PATH")

        # Tup requires .tup/ directory to be initialized
        if not os.path.isdir(".tup"):
            subprocess.check_call(["tup", "init"], universal_newlines=True)

        cmd = ["tup"]
        parallel = getattr(self.args, "parallel", None)
        if parallel:
            cmd.extend(["-j", str(parallel)])
        subprocess.check_call(cmd, universal_newlines=True)
